#!/usr/bin/env python3
"""Per-sport factsheet generator. For each sport with >= 3 rows in master.csv,
emit a one-page summary at outputs/sport_factsheets/<sport>.md.

Each factsheet covers:
  - One-line summary (rows, sources, year span, geography)
  - All rows with extractable per-1000-AE rates (table)
  - Mouthguard data summary
  - Age + sex distribution
  - Caveats per the sport
"""

import csv
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "data/harmonized/master.csv"
OUT_DIR = ROOT / "outputs/sport_factsheets"
OUT_DIR.mkdir(parents=True, exist_ok=True)

rows = list(csv.DictReader(open(MASTER)))

by_sport = defaultdict(list)
for r in rows:
    s = r["sport"]
    if not s or s.startswith(("all_sports_", "all_activities_", "sports_",
                              "non_sport", "recreational_")):
        continue
    by_sport[s].append(r)


def f_pct(n, d):
    return f"{n}/{d} ({100*n/d:.0f}%)" if d else "0/0"


index_lines = ["# Per-sport factsheets\n",
               "_One-page Markdown summary per sport with ≥3 rows in master.csv. "
               "Auto-generated by `scripts/24_sport_factsheets.py`._\n",
               "| sport | rows | sources | year span | countries |",
               "|---|---:|---:|---|---|"]


for sport in sorted(by_sport):
    sport_rows = by_sport[sport]
    if len(sport_rows) < 3:
        continue

    sources = sorted({r["source_id"] for r in sport_rows})
    countries = sorted({r["country"] for r in sport_rows if r["country"]})
    years = sorted({int(r["pub_year"]) for r in sport_rows if r["pub_year"].isdigit()})
    year_span = f"{min(years)}-{max(years)}" if years else "—"

    index_lines.append(f"| [{sport}]({sport}.md) | {len(sport_rows)} | "
                       f"{len(sources)} | {year_span} | {', '.join(countries) or '—'} |")

    # Per-sport markdown
    md = [f"# {sport.replace('_', ' ').title()} — Factsheet\n",
          f"_Auto-generated from `master.csv`. {len(sport_rows)} rows across {len(sources)} sources._\n",
          f"**Sport identifier in database:** `{sport}`"]
    if sport_rows:
        cat = sport_rows[0].get("sport_category", "") or "(unset)"
        md.append(f"**Sport category:** `{cat}`")
    md.append(f"**Countries:** {', '.join(countries) or '—'}")
    md.append(f"**Year span:** {year_span}")
    md.append(f"**Sources contributing:** {', '.join(sources)}\n")

    # ----- Rate-bearing rows -----
    rate_rows = [r for r in sport_rows
                 if r["rate_per_1000_ae"] and r["rate_per_1000_ae"] != ""]
    if rate_rows:
        md.append("## Rates per 1000 athlete-exposures\n")
        md.append("| source | year | country | age | sex | level | rate /1000 AE | subgroup | denominator |")
        md.append("|---|---:|---|---|---|---|---:|---|---|")
        for r in sorted(rate_rows, key=lambda r: float(r["rate_per_1000_ae"])):
            md.append(f"| {r['source_id']} | {r['pub_year']} | {r['country'] or '—'} | "
                      f"{r['age_category'] or '—'} | {r['sex'] or '—'} | "
                      f"{r['level_of_play'] or '—'} | "
                      f"**{float(r['rate_per_1000_ae']):.3f}** | "
                      f"{r.get('subgroup_label') or '—'} | "
                      f"{(r.get('rate_denominator_raw') or '')[:60]} |")
        rates = [float(r["rate_per_1000_ae"]) for r in rate_rows]
        md.append(f"\n_Min {min(rates):.3f}, max {max(rates):.3f}, n={len(rates)}._\n")
    else:
        md.append("## Rates per 1000 athlete-exposures\n")
        md.append("_No rows with `rate_per_1000_ae` populated. See `rate_raw` + `rate_denominator_raw` for source-original rates with non-AE denominators._\n")

    # ----- Mouthguard data -----
    mg_rows = [r for r in sport_rows
               if r["mouthguard_use_rate"] and r["mouthguard_use_rate"] != ""]
    if mg_rows:
        md.append("## Mouthguard use\n")
        md.append("| source | year | sex | subgroup | use rate | injury-relation analysis |")
        md.append("|---|---:|---|---|---:|---|")
        for r in sorted(mg_rows, key=lambda r: -float(r["mouthguard_use_rate"])):
            try:
                use = float(r["mouthguard_use_rate"])
            except ValueError:
                continue
            md.append(f"| {r['source_id']} | {r['pub_year']} | {r['sex'] or '—'} | "
                      f"{r.get('subgroup_label') or '—'} | **{use:.0%}** | "
                      f"{r['mouthguard_injury_relation'] or '—'} |")
        md.append("")

    # ----- Age + sex distribution of rows -----
    age_counts = Counter(r["age_category"] for r in sport_rows if r["age_category"])
    sex_counts = Counter(r["sex"] for r in sport_rows if r["sex"])
    md.append("## Distribution of rows\n")
    md.append("| age_category | count |     | sex | count |")
    md.append("|---|---:|---|---|---:|")
    for ac, sc in zip(sorted(age_counts.items()), sorted(sex_counts.items())):
        md.append(f"| {ac[0]} | {ac[1]} | | {sc[0]} | {sc[1]} |")
    # If lists differ in length pad
    if len(age_counts) != len(sex_counts):
        md.append("")  # avoid table-misalignment in renderers

    # ----- Raw injury counts -----
    inj_total = 0
    for r in sport_rows:
        try:
            inj_total += int(float(r["injury_count"])) if r["injury_count"] else 0
        except ValueError:
            pass
    md.append(f"\n_Cumulative reported `injury_count` across these {len(sport_rows)} rows: **{inj_total:,}**._\n")
    md.append("Note: rows may double-count cases (e.g., aggregate row + per-sex breakdown of the same cohort). Use unique source-level reasoning when citing.\n")

    md.append("## Related sources outside this sport\n")
    md.append("Cross-sport sources reporting an aggregate that includes this sport are tagged "
              "`sport = all_sports_aggregate` in master.csv with a note in `extraction_notes`. "
              "Search master.csv for `extraction_notes` mentioning this sport name to find them.\n")
    md.append("## Provenance\n")
    md.append(f"Generated by `scripts/24_sport_factsheets.py` from `data/harmonized/master.csv`. "
              f"Sources of truth: each row's `source_id` → `data/extracted/<source_id>.csv` → "
              f"original publication / surveillance system per row's `citation`.\n")

    (OUT_DIR / f"{sport}.md").write_text("\n".join(md))

# Write index
(OUT_DIR / "README.md").write_text("\n".join(index_lines) + "\n")
print(f"Wrote {len([s for s in by_sport if len(by_sport[s]) >= 3])} sport factsheets to {OUT_DIR.relative_to(ROOT)}")
