#!/usr/bin/env python3
"""Generate outputs/sources_bibliography.bib — BibTeX entries for every
screened_included PubMed source.

For each PMID, reads the per-PMID JSON in data/raw/papers/_abstracts/ and
emits a BibTeX @article entry. Citation key = source_id where known, else
PMID.

Includes a separate @misc entry per governing-body source from
docs/governing_body_sources.md.
"""

import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ABS = ROOT / "data/raw/papers/_abstracts"
DEC = ROOT / "data/extracted/_screening/screening_decisions.csv"
OUT = ROOT / "outputs/sources_bibliography.bib"


# Map PMID -> source_id, parsed from docs/sources.md (authoritative; generated
# by scripts/03 from the PubMed first author). Parsed rather than hardcoded so
# the BibTeX keys cannot drift out of sync with the dataset — a hardcoded map
# here previously carried fabricated ids (williams2024, collins2004, ...); see
# docs/decisions.md 2026-06-16.
_SOURCES_MD = ROOT / "docs/sources.md"
PMID_TO_SOURCE_ID = {}
for _line in _SOURCES_MD.read_text().splitlines():
    _m = re.match(r"^\|\s*([A-Za-z0-9_\-]+)\s*\|\s*\[(\d+)\]", _line)
    if _m:
        PMID_TO_SOURCE_ID[_m.group(2)] = _m.group(1)


def escape_bib(s):
    """Escape BibTeX special chars in a string."""
    return (s or "").replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")


def parse_authors(rec):
    """Return BibTeX 'Last, FM and Last, FM and ...' format."""
    authors = rec.get("authors") or []
    parts = []
    for a in authors:
        a = a.strip()
        if not a: continue
        # esummary format: "LastName Initials"
        m = re.match(r"^(\S+(?:\s\S+)*?)\s+([A-Z][A-Z]?)$", a)
        if m:
            parts.append(f"{m.group(1)}, {m.group(2)}")
        else:
            parts.append(a)
    return " and ".join(parts) if parts else "Unknown"


def get_doi(pmid):
    """Pull DOI from esummary JSON."""
    summary = ROOT / "data/raw/papers/_search_logs/pubmed_esummary_2026-05-21.json"
    if not summary.exists():
        return ""
    try:
        data = json.load(open(summary))
        rec = data.get("result", {}).get(pmid, {})
        for art in rec.get("articleids", []):
            if art.get("idtype") == "doi":
                return art.get("value", "")
    except (json.JSONDecodeError, KeyError):
        pass
    return ""


# Build BibTeX entries
# Every source that cleared screening belongs in the bibliography: the
# abstract-screen "screened_included" pile plus records promoted to "included"
# by full-text review (e.g. halabchi2007, resolved 2026-06-12).
rows = list(csv.DictReader(open(DEC)))
BIB_DECISIONS = {"screened_included", "included"}
included = [r["pmid"] for r in rows if r["decision"] in BIB_DECISIONS]
print(f"Building bibliography for {len(included)} included/screened_included PMIDs")

entries = []
header = f"""% Bibliography for the Youth Sports Dental Injury Database
% Auto-generated by scripts/26_bibliography.py
% Source: every PMID screened_included or promoted to included by full-text review
% Last generated: 2026-06-12
%
% Citation keys match source_id (e.g., @article{{collins2016}}); else fall back to PMID.
% To use: \\cite{{collins2016}} or \\cite{{PMID-22260909}}
"""

skipped = 0
for pmid in sorted(included):
    f = ABS / f"{pmid}.json"
    if not f.exists():
        skipped += 1
        continue
    rec = json.load(open(f))
    key = PMID_TO_SOURCE_ID.get(pmid, f"PMID-{pmid}")
    title = escape_bib(rec.get("title", "Untitled"))
    authors = escape_bib(parse_authors(rec))
    journal = escape_bib(rec.get("journal", ""))
    year = rec.get("pub_year", "")
    doi = get_doi(pmid)

    e = [f"@article{{{key},",
         f"  title   = {{{title}}},",
         f"  author  = {{{authors}}},",
         f"  journal = {{{journal}}},",
         f"  year    = {{{year}}},",
         f"  pmid    = {{{pmid}}},"]
    if doi:
        e.append(f"  doi     = {{{doi}}},")
        e.append(f"  url     = {{https://doi.org/{doi}}},")
    else:
        e.append(f"  url     = {{https://pubmed.ncbi.nlm.nih.gov/{pmid}/}},")
    e.append("}\n")
    entries.append("\n".join(e))

# Governing-body sources (curated set)
gov_entries = [
    """@misc{neiss_cpsc,
  title        = {National Electronic Injury Surveillance System (NEISS)},
  author       = {{US Consumer Product Safety Commission}},
  year         = {2025},
  note         = {Online query system, data 2006--2025; case-level filtered extracts for 2013--2017 (via the hadley/neiss R-package archive) and 2018--2025 (via direct CPSC query) are part of this database},
  url          = {https://www.cpsc.gov/cgibin/NEISSQuery/},
}
""",
    """@misc{hadley_neiss,
  title        = {neiss: Data from the National Electronic Injury Surveillance System},
  author       = {Wickham, Hadley},
  year         = {2017},
  note         = {R package containing 2013--2017 NEISS injury data},
  url          = {https://github.com/hadley/neiss},
}
""",
    """@misc{rio_pipertm,
  title        = {National High School Sports-Related Injury Surveillance Study},
  author       = {{Center for Injury Research and Policy} and {PIPER Program, Colorado School of Public Health}},
  year         = {2024},
  note         = {Annual summary reports 2008--2019, 2021--2024; ten reports cached in this database under data/raw/surveillance_reports/},
  url          = {https://coloradosph.cuanschutz.edu/research-and-practice/centers-programs/piper},
}
""",
    """@misc{aapd_2025_policy,
  title        = {Policy on Prevention of Sports-Related Orofacial Injuries},
  author       = {{American Academy of Pediatric Dentistry}},
  year         = {2025},
  note         = {2025--2026 edition (last revised 2023); 79 numbered references},
  url          = {https://www.aapd.org/media/policies_guidelines/p_sports.pdf},
}
""",
    """@misc{rugby_europe_iss_2024,
  title        = {Injury Surveillance Report, March 2024},
  author       = {{Rugby Europe}},
  year         = {2024},
  note         = {2022/23 Rugby Europe Sevens; includes U-18 Men's and Women's Championship + Trophy injury surveillance},
  url          = {https://www.rugbyeurope.eu/media/gxwdngx2/re-injury-surveillance-report-march-2024.pdf},
}
""",
]

OUT.write_text(header + "\n".join(entries) + "\n% ---- Governing-body / surveillance ----\n\n" + "\n".join(gov_entries))
print(f"Wrote {OUT.relative_to(ROOT)} — {len(entries)} @article + {len(gov_entries)} @misc entries (skipped {skipped} PMIDs without abstract JSON)")
