#!/usr/bin/env python3
"""Generate outputs/sources_bibliography.bib — BibTeX entries for every
screened_included PubMed source.

For each PMID, reads the per-PMID JSON in data/raw/papers/_abstracts/ and
emits a BibTeX @article entry. Citation key = source_id where known, else
PMID.

Includes a separate @misc entry per governing-body source from
docs/governing_body_sources.md.
"""

import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ABS = ROOT / "data/raw/papers/_abstracts"
DEC = ROOT / "data/extracted/_screening/screening_decisions.csv"
OUT = ROOT / "outputs/sources_bibliography.bib"


# Map PMID -> source_id where known (so the BibTeX key matches our naming)
PMID_TO_SOURCE_ID = {
    "26408377": "collins2016",     "11782645": "labella2002",
    "19614738": "stewart2009",     "36317716": "azadani2023",
    "31506903": "quarrie2020",     "21197817": "welch2010",
    "41501720": "hamdan2026",      "38131151": "udayamalee2024",
    "33848349": "vanierssel2021",  "29403232": "goswami2017",
    "29284466": "tsuchiya2017",    "25520762": "singh2014",
    "21457187": "chan2011",        "18821957": "cetinbas2008",
    "17991235": "levin2007",       "36394781": "shore2023",
    "15876321": "amy2005",         "14708646": "levin2003",
    "40771058": "cetin2026",       "37818921": "williams2024",
    "37743045": "williams2023",    "36929194": "nasu2023",
    "34643329": "mooney2021",      "33746633": "naasan2021",
    "33292522": "azimi2020",       "31765062": "calderon2020",
    "29526055": "zaror2018",       "26093006": "yard2015",
    "25500920": "deshpande2014",   "23532813": "yildirim2013",
    "23045787": "mcevoy2012",      "21063551": "zazryn2010",
    "19290905": "naidoo2009",      "19030141": "yard2008",
    "18821952": "mcdonough2008",   "18689347": "mahlangu2008",
    "17670881": "trinidad2007",    "11499758": "mate2001",
    "8883693": "hosea1996",        "15592602": "collins2004",
    "16809595": "pattussi2006",    "11202877": "carter2000",
    "11678540": "marcenes2001",    "11798994": "benson2002",
    "15660753": "ranalli2005",     "16162986": "mcintosh2005",
    "17073918": "nalcaci2006",     "17635356": "ali2007",
    "18203866": "collins_rugby2008", "18410389": "wong2008",
    "18721348": "livny2008",       "19208012": "fakhruddin2009",
    "19566982": "yamada2009",      "20486946": "hayran2010",
    "22976571": "ivanovics2012",   "11003192": "danis2000",
    "15178672": "chapman2004",     "16081755": "finch2005",
    "18519488": "collins_baseball2008", "22260909": "leite2012",
    "24813778": "alotaibi2014",    "32866487": "baek2021",
    "33614796": "alawawdeh2021",   "34973164": "alawawdeh2022",
    "35340727": "wormald2022",     "8784371": "radelet1996",
    "9191640": "emshoff1997",      "31179757": "collins_neiss2019",
    "34879017": "kaplan2022",      "33710051": "rajan2021",
    "33710063": "ekanayake2021",   "33741876": "dafnis_soccer2021",
    "33654038": "basketball_craniofacial2021",
    "31937578": "chisholm2020",    "30865370": "alkilzy2019",
    "27452795": "otsuru2016",      "25881567": "kanagasingam2016",
}


def escape_bib(s):
    """Escape BibTeX special chars in a string."""
    return (s or "").replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")


def parse_authors(rec):
    """Return BibTeX 'Last, FM and Last, FM and ...' format."""
    authors = rec.get("authors") or []
    parts = []
    for a in authors:
        a = a.strip()
        if not a: continue
        # esummary format: "LastName Initials"
        m = re.match(r"^(\S+(?:\s\S+)*?)\s+([A-Z][A-Z]?)$", a)
        if m:
            parts.append(f"{m.group(1)}, {m.group(2)}")
        else:
            parts.append(a)
    return " and ".join(parts) if parts else "Unknown"


def get_doi(pmid):
    """Pull DOI from esummary JSON."""
    summary = ROOT / "data/raw/papers/_search_logs/pubmed_esummary_2026-05-21.json"
    if not summary.exists():
        return ""
    try:
        data = json.load(open(summary))
        rec = data.get("result", {}).get(pmid, {})
        for art in rec.get("articleids", []):
            if art.get("idtype") == "doi":
                return art.get("value", "")
    except (json.JSONDecodeError, KeyError):
        pass
    return ""


# Build BibTeX entries
# Every source that cleared screening belongs in the bibliography: the
# abstract-screen "screened_included" pile plus records promoted to "included"
# by full-text review (e.g. halabchi2007, resolved 2026-06-12).
rows = list(csv.DictReader(open(DEC)))
BIB_DECISIONS = {"screened_included", "included"}
included = [r["pmid"] for r in rows if r["decision"] in BIB_DECISIONS]
print(f"Building bibliography for {len(included)} included/screened_included PMIDs")

entries = []
header = f"""% Bibliography for the Youth Sports Dental Injury Database
% Auto-generated by scripts/26_bibliography.py
% Source: every PMID screened_included or promoted to included by full-text review
% Last generated: 2026-06-12
%
% Citation keys match source_id (e.g., @article{{collins2016}}); else fall back to PMID.
% To use: \\cite{{collins2016}} or \\cite{{PMID-22260909}}
"""

skipped = 0
for pmid in sorted(included):
    f = ABS / f"{pmid}.json"
    if not f.exists():
        skipped += 1
        continue
    rec = json.load(open(f))
    key = PMID_TO_SOURCE_ID.get(pmid, f"PMID-{pmid}")
    title = escape_bib(rec.get("title", "Untitled"))
    authors = escape_bib(parse_authors(rec))
    journal = escape_bib(rec.get("journal", ""))
    year = rec.get("pub_year", "")
    doi = get_doi(pmid)

    e = [f"@article{{{key},",
         f"  title   = {{{title}}},",
         f"  author  = {{{authors}}},",
         f"  journal = {{{journal}}},",
         f"  year    = {{{year}}},",
         f"  pmid    = {{{pmid}}},"]
    if doi:
        e.append(f"  doi     = {{{doi}}},")
        e.append(f"  url     = {{https://doi.org/{doi}}},")
    else:
        e.append(f"  url     = {{https://pubmed.ncbi.nlm.nih.gov/{pmid}/}},")
    e.append("}\n")
    entries.append("\n".join(e))

# Governing-body sources (curated set)
gov_entries = [
    """@misc{neiss_cpsc,
  title        = {National Electronic Injury Surveillance System (NEISS)},
  author       = {{US Consumer Product Safety Commission}},
  year         = {2025},
  note         = {Online query system, data 2006--2025; case-level filtered extracts for 2013--2017 (via the hadley/neiss R-package archive) and 2018--2025 (via direct CPSC query) are part of this database},
  url          = {https://www.cpsc.gov/cgibin/NEISSQuery/},
}
""",
    """@misc{hadley_neiss,
  title        = {neiss: Data from the National Electronic Injury Surveillance System},
  author       = {Wickham, Hadley},
  year         = {2017},
  note         = {R package containing 2013--2017 NEISS injury data},
  url          = {https://github.com/hadley/neiss},
}
""",
    """@misc{rio_pipertm,
  title        = {National High School Sports-Related Injury Surveillance Study},
  author       = {{Center for Injury Research and Policy} and {PIPER Program, Colorado School of Public Health}},
  year         = {2024},
  note         = {Annual summary reports 2008--2019, 2021--2024; ten reports cached in this database under data/raw/surveillance_reports/},
  url          = {https://coloradosph.cuanschutz.edu/research-and-practice/centers-programs/piper},
}
""",
    """@misc{aapd_2025_policy,
  title        = {Policy on Prevention of Sports-Related Orofacial Injuries},
  author       = {{American Academy of Pediatric Dentistry}},
  year         = {2025},
  note         = {2025--2026 edition (last revised 2023); 79 numbered references},
  url          = {https://www.aapd.org/media/policies_guidelines/p_sports.pdf},
}
""",
    """@misc{rugby_europe_iss_2024,
  title        = {Injury Surveillance Report, March 2024},
  author       = {{Rugby Europe}},
  year         = {2024},
  note         = {2022/23 Rugby Europe Sevens; includes U-18 Men's and Women's Championship + Trophy injury surveillance},
  url          = {https://www.rugbyeurope.eu/media/gxwdngx2/re-injury-surveillance-report-march-2024.pdf},
}
""",
]

OUT.write_text(header + "\n".join(entries) + "\n% ---- Governing-body / surveillance ----\n\n" + "\n".join(gov_entries))
print(f"Wrote {OUT.relative_to(ROOT)} — {len(entries)} @article + {len(gov_entries)} @misc entries (skipped {skipped} PMIDs without abstract JSON)")
