#!/usr/bin/env python3
"""Generate a Frictionless Data tabular data package descriptor (datapackage.json).

Emits a standards-compliant `datapackage.json` at the repo root describing
`data/harmonized/master.csv`: field names, types inferred from the data, and
field descriptions parsed from DATA_DICTIONARY.md, plus dataset metadata and the
CC BY 4.0 data licence. This makes the dataset machine-consumable by the
Frictionless toolchain and repositories (Zenodo, CKAN, etc.) and is a common
expectation for open data descriptors.

Read-only w.r.t. the data. Regenerated by `scripts/run_all.py`.
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "data/harmonized/master.csv"
DICT = ROOT / "DATA_DICTIONARY.md"
OUT = ROOT / "datapackage.json"


def infer_type(values) -> str:
    vals = [v.strip() for v in values if v.strip() not in ("", "NA")]
    if not vals:
        return "string"
    if all(v in ("TRUE", "FALSE") for v in vals):
        return "boolean"
    def is_int(v):
        return re.fullmatch(r"-?\d+", v) is not None
    def is_num(v):
        return re.fullmatch(r"-?\d+(\.\d+)?", v) is not None
    if all(is_int(v) for v in vals):
        return "integer"
    if all(is_num(v) for v in vals):
        return "number"
    return "string"


def parse_descriptions() -> dict:
    """Field -> description from the DATA_DICTIONARY markdown tables."""
    desc = {}
    for line in DICT.read_text().splitlines():
        m = re.match(r"^\|\s*`([a-z_]+)`\s*\|[^|]*\|\s*(.+?)\s*\|", line)
        if m:
            d = re.sub(r"`([^`]*)`", r"\1", m.group(2))       # strip backticks
            d = re.sub(r"\*\*([^*]*)\*\*", r"\1", d)           # strip bold
            desc[m.group(1)] = d.strip()
    return desc


def main() -> None:
    rows = list(csv.DictReader(open(MASTER)))
    header = list(rows[0].keys())
    desc = parse_descriptions()

    fields = []
    for col in header:
        f = {"name": col, "type": infer_type([r.get(col, "") for r in rows])}
        if desc.get(col):
            f["description"] = desc[col][:500]
        fields.append(f)

    n_sources = len({r["source_id"] for r in rows})
    countries = sorted({r["country"].strip() for r in rows if r["country"].strip()})

    pkg = {
        "name": "youth-sports-dental-injury-database",
        "title": "Youth Sports Dental Injury Database",
        "description": (
            f"Harmonized open-access database of dental and orofacial injury "
            f"epidemiology in youth sports (ages 5-22): {len(rows)} data points from "
            f"{n_sources} sources (peer-reviewed studies, national injury surveillance, "
            f"and governing-body reports) across {len(countries)} countries. Each row is "
            f"one extracted statistic with population, exposure, outcome, mouthguard, "
            f"comparability, provenance, and dental-specificity metadata."),
        "homepage": "https://github.com/Vihaan-Banga/youth-dental-injury-database",
        "version": "0.1.0-dev",
        "keywords": ["dental trauma", "orofacial injury", "sports injury", "youth",
                     "adolescent", "mouthguard", "epidemiology", "NEISS",
                     "injury surveillance", "sports dentistry"],
        "licenses": [{
            "name": "CC-BY-4.0",
            "title": "Creative Commons Attribution 4.0 International",
            "path": "https://creativecommons.org/licenses/by/4.0/",
        }],
        "resources": [{
            "name": "master",
            "path": "data/harmonized/master.csv",
            "format": "csv",
            "mediatype": "text/csv",
            "encoding": "utf-8",
            "title": "Harmonized master dataset",
            "schema": {
                "fields": fields,
                "primaryKey": ["source_id", "sport", "age_category", "sex",
                               "level_of_play", "extraction_basis",
                               "exposure_context", "subgroup_label",
                               "season_or_timeframe"],
                "missingValues": [""],
            },
        }],
    }
    OUT.write_text(json.dumps(pkg, indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(fields)} fields, "
          f"{sum(1 for f in fields if 'description' in f)} with descriptions.")


if __name__ == "__main__":
    main()
