"""AI-assisted screening decisions for the 200 PubMed candidates seeded 2026-05-21.

Each entry is keyed by PMID and produces a tuple of
(decision, reason_code, confidence, note).

These decisions were made by reading title + abstract + publication-type
metadata only. They are NOT a substitute for full-text review by the project
lead. Specifically:
  - 'screened_included' here means the abstract suggests the source meets
    PROTOCOL §3.1–3.3 criteria; the source still goes through full-text review.
  - 'screened_excluded' is a confident exclusion based on the abstract.
  - 'needs_human_review' flags abstracts where a key inclusion attribute
    (age range, sport-related subset, primary numerical data) could not be
    confirmed from the abstract alone.

The 44 automatic exclusions (non-English, Case Reports, Reviews/SR/MA) are
handled by 02_screen_candidates.py's auto rules and do not appear here.

Confidence levels:
  high   — abstract clearly supports the decision; further review unlikely to change it
  medium — abstract supports the decision but a full-text reader could plausibly disagree
  low    — used only for needs_human_review where the abstract is genuinely ambiguous
"""

MANUAL_DECISIONS: dict[str, tuple[str, str, str, str]] = {

    # --------------------- INCLUDES (high confidence) ---------------------

    "11202877": ("screened_included", "I-pri", "high",
        "Schoolchildren n=2022, sport-related causes ~30% of TDI; primary epidemiology data, age range consistent with 5–18."),
    "11499758": ("screened_included", "I-pri", "high",
        "Children 7–14 (88% of 590-child cohort); sports listed as etiology with frequency rank; primary data extractable for sport subset."),
    "11678540": ("screened_included", "I-pri", "high",
        "n=652 13-year-old adolescents Brazil; sport-related = 2.3% of TDI etiology; meets §3.1 age + sport + numerical data."),
    "11782645": ("screened_included", "I-pri", "high",
        "Prospective study of 50 NCAA Div I men's college basketball teams; reports dental injury rates/1000 AE with mouthguard effect — gold-standard fit (sport=basketball, age=collegiate, primary AE-denominator data)."),
    "14708646": ("screened_included", "I-pri", "high",
        "n=943 young adults ages 18–19 Israel; sport-specific dental injury counts (soccer, basketball) + mouthguard awareness — perfect §3.1 fit."),
    "15022997": ("screened_included", "I-pri", "high",
        "Norwegian children 7–18, n=1275 injured individuals; sport = 8% of dental injury etiology; primary data extractable."),
    "15592602": ("screened_included", "I-pri", "high",
        "Punahou School longitudinal 1988–2003 intermediate+HS athletes; dental injury rates/1000 athlete-sessions by sport — directly extractable AE-denominator data."),
    "15660753": ("screened_included", "I-pri", "high",
        "Turkish Premier Ice Hockey League youth AND adult players — youth subset is extractable per the abstract's explicit framing."),
    "15876321": ("screened_included", "I-pri", "high",
        "20-year experience of dental services at Central American & Caribbean Games; sport-related orofacial injuries reported across multiple sports."),
    "16162986": ("screened_included", "I-pri", "high",
        "Multicenter cluster-RCT, varsity football and rugby teams, mouthguard vs mouthguard, concussion + dental trauma outcomes per playing season — high-quality primary data."),
    "16809595": ("screened_included", "I-pri", "high",
        "Brazilian adolescents 14–15 n=1302 multilevel study; dental injury as outcome — likely sport-related subset extractable from full text."),
    "17073918": ("screened_included", "I-pri", "high",
        "Pony/horseback riding children, n=214; sport-specific dental trauma prevalence reported."),
    "17635356": ("screened_included", "I-pri", "high",
        "Glasgow pediatric dental trauma audit; abstract reports 79% of sporting-related injuries were in males — sport-specific data extractable."),
    "17670881": ("screened_included", "I-pri", "high",
        "USC intercollegiate athletes 1996–2005, n=51 dental injuries with sport-level detail; college = within 18–22 age range."),
    "17991235": ("screened_included", "I-pri", "high",
        "n=427 young adults ages 18–21 Israel; sport-specific dental injury counts + mouthguard data."),
    "18410389": ("screened_included", "I-pri", "high",
        "Population-based case-comparison study of n=2422 Ontario schoolchildren ages 12 and 14; primary etiology data."),
    "18689347": ("screened_included", "I-pri", "high",
        "Schoolchildren 10–14 Maseru Lesotho; permanent incisor TDI prevalence and etiology."),
    "18721348": ("screened_included", "I-pri", "high",
        "5th–6th grade Arab schoolchildren Jerusalem n=453; TDI prevalence + etiology."),
    "18821957": ("screened_included", "I-pri", "high",
        "n=2570 Ankara schoolchildren ages 7–9 and 11–13; specifically studies the role of sport in crown fractures."),
    "19030141": ("screened_included", "I-pri", "high",
        "RIO surveillance HS athletes 2005/06 and 2006/07; dental injuries are one of the RIC categories reported."),
    "19208012": ("screened_included", "I-pri", "high",
        "Random sample of n=6312 Taiwanese 15–18 yr senior HS students; TDI prevalence + activity-related etiology."),
    "19290905": ("screened_included", "I-pri", "high",
        "Random cluster sample of n=2610 South African 11–13 schoolchildren; TDI prevalence."),
    "19566982": ("screened_included", "I-pri", "high",
        "n=411 schoolboy cricketers at 8 private schools England + Australia; head/face/dental prevalence by country — strong sport+age fit."),
    "19614738": ("screened_included", "I-pri", "high",
        "NEISS analysis 1990–2003 of dental injuries to children 0–17; consumer products + activities including sport — primary surveillance dataset."),
    "20486946": ("screened_included", "I-pri", "high",
        "Snowboarders Turkey n=86; framed as 'adolescent and young adult' — within 5–22 envelope."),
    "21197817": ("screened_included", "I-pri", "high",
        "NZ ACC sports-related dental insurance claims 1999–2008; ~25–31k claims/year with age/sex/region/sport breakdown — large-scale surveillance, youth subset extractable."),
    "21299945": ("screened_included", "I-pri", "high",
        "Cork University Dental School pediatric trauma audit; cause and prevalence by type — primary clinical data."),
    "21457187": ("screened_included", "I-pri", "high",
        "Dunedin NZ children 0–10 orofacial trauma audit; sport contributes to causes in older subgroup."),
    "22976571": ("screened_included", "I-pri", "high",
        "Targu Mures retrospective study, ages 1–18, with physical-activity risk factor — youth-specific TDI data."),
    "23045787": ("screened_included", "I-pri", "high",
        "n=1111 Irish children ages 9–13; mouthguard use + dental trauma in sport — directly addresses §3.3."),
    "23532813": ("screened_included", "I-pri", "high",
        "Pediatric handball players Istanbul amateur national league; TDI frequency + mouthguard knowledge — sport + youth fit."),
    "25500920": ("screened_included", "I-pri", "high",
        "Cross-sectional athletes 12–22 in central India contact vs noncontact; mouthguard awareness + injury rates — perfect §3.1 age + sport fit."),
    "25520762": ("screened_included", "I-pri", "high",
        "n=cross-sectional HS students 8–16 in North India organized sports teams; sport-related orodental injury prevalence."),
    "25881567": ("screened_included", "I-pri", "high",
        "n=494 junior rugby league players + coaches Gold Coast; knowledge + TDI experience — junior population fits."),
    "26093006": ("screened_included", "I-pri", "high",
        "Collegiate women's field hockey head/face/eye injury epidemiology; college age within 18–22 — direct sport+age fit."),
    "26408377": ("screened_included", "I-pri", "high",
        "National HS Sports-Related Injury Surveillance Study 2008/09–2013/14; n=222 dental injuries with AE-denominator data per sport — gold-standard."),
    "27452795": ("screened_included", "I-pri", "high",
        "Japan junior HS + HS school sports clubs dental injury risk by sport; school-age population (mostly 12–18)."),
    "28054391": ("screened_included", "I-pri", "high",
        "Prospective cohort study of organized football in 7–12 yr children across 4 European countries; head/neck injuries documented — age fit + sport-specific."),
    "29284466": ("screened_included", "I-pri", "high",
        "School-aged athletes Miyagi prefecture Japan; sports-related dental injury prevalence + risk factors — explicit §3.3 outcome."),
    "29403232": ("screened_included", "I-pri", "high",
        "n=450 children 6–16 New Delhi; dental injury prevalence during sport + mouthguard awareness — direct fit."),
    "29406619": ("screened_included", "I-pri", "high",
        "Hockey Alberta surveillance 2001–2016 'all ages'; rates + mechanisms — youth subset extractable from governing-body dataset."),
    "29526055": ("screened_included", "I-pri", "high",
        "n=229 young athletes 4 contact sports (water polo/karate/taekwondo/handball); sport-related dental injury + mouthguard."),
    "30865370": ("screened_included", "I-pri", "high",
        "Amateur soccer players 7–18 Kuwait; TDI prevalence/type/causes — perfect age + sport fit."),
    "31179757": ("screened_included", "I-pri", "high",
        "NEISS pediatric sports/recreation dental injuries treated in US EDs — large-scale surveillance, exactly the kind of source PROTOCOL §4.1 targets."),
    "31228311": ("screened_included", "I-pri", "high",
        "n=2055 16-yr-old Norwegian pupils retrospective longitudinal TDI; life-course risk factors."),
    "31506903": ("screened_included", "I-pri", "high",
        "NZ ACC rugby injury claims 2005–2017 ages 5–40 with differences by age — large surveillance, youth subset (5–22) directly extractable."),
    "31624810": ("screened_included", "I-pri", "high",
        "Lithuanian 11–13 schoolchildren with focus on contact-sport mouthguard use; TDI prevalence + sport-specific data."),
    "31765062": ("screened_included", "I-pri", "high",
        "n=325 Catalonia field hockey players 'all age categories' incl. women; sport-specific orofacial injury + mouthguard data."),
    "33292522": ("screened_included", "I-pri", "high",
        "Children 6–13 Hamadan Iran sports-related dental injury study (random forest); primary data on athletes."),
    "33654038": ("screened_included", "I-pri", "high",
        "10-yr NEISS retrospective cohort of basketball-related craniofacial injuries; on-court management focus but primary epi data available."),
    "33710051": ("screened_included", "I-pri", "high",
        "n=682 NCAA Division I college athletes Columbia; dento-facial injury + concussion + mouthguard — college fits."),
    "33710063": ("screened_included", "I-pri", "high",
        "10-yr NEISS amateur ice hockey craniofacial injuries; explicit youth/amateur/professional breakdown — youth subset extractable."),
    "33741876": ("screened_included", "I-pri", "high",
        "10-yr NEISS soccer craniofacial injuries with demographic stratification — youth subset extractable."),
    "33746633": ("screened_included", "I-pri", "high",
        "n=7902 12- and 15-yr-old Lebanese schoolchildren national TDI study — large sample, perfect age fit."),
    "33848349": ("screened_included", "I-pri", "high",
        "Prospective cohort 9 Canadian pediatric EDs, ages 5–18 with sport-related concussion + mouthguard outcomes — direct §3.3 fit."),
    "34643329": ("screened_included", "I-pri", "high",
        "Cross-sectional observational cohort 9–16 yr Gaelic football children + parents; MG knowledge + dental trauma."),
    "34879017": ("screened_included", "I-pri", "high",
        "NEISS baseball craniofacial injuries youth (5–19) — perfect §3.1 age + sport fit, primary surveillance dataset."),
    "36317716": ("screened_included", "I-pri", "high",
        "National HS Sports-Related Injury Surveillance Study 2005/06–2019/20; dental injury counts + AE + mouthguard utilization — directly extractable."),
    "36428271": ("screened_included", "I-pri", "high",
        "n=7684 Japan school dental injury cases over 15 years across 5 sports — large governing-body surveillance dataset."),
    "36929194": ("screened_included", "I-pri", "high",
        "Japan school head injuries from tooth contact 2012–2018; school-age population by definition; primary count data."),
    "37743045": ("screened_included", "I-pri", "high",
        "NEISS retrospective 2003–2022 soccer craniomaxillofacial injuries; demographic stratification — youth subset extractable."),
    "37818921": ("screened_included", "I-pri", "high",
        "NEISS basketball dental injury mechanisms 2003–2022; primary mechanism data."),
    "38131151": ("screened_included", "I-pri", "high",
        "n=1340 adolescent contact-sport players Colombo Sri Lanka; oro-dental trauma burden + mouthguard usage — perfect §3.1 fit."),
    "39297708": ("screened_included", "I-pri", "high",
        "Sydney tertiary hospital 2001–2021 avulsion cohort, median age 12 (IQR 9–17); non-organized sport = most common cause — youth + sport fit."),
    "40655786": ("screened_included", "I-pri", "high",
        "Retrospective 100-case sports-related dental trauma study with focus on children/adolescents and contact sports."),
    "40771058": ("screened_included", "I-pri", "high",
        "n=125 youth basketball players Turkey 2024–25 season; TDI prevalence + mouthguard knowledge — direct §3.1 fit."),
    "40917008": ("screened_included", "I-pri", "high",
        "n=582 Syrian child athletes 6–16; orofacial-dental trauma prevalence + injury patterns + protective gear — direct §3.1 fit."),
    "41501720": ("screened_included", "I-pri", "high",
        "n=445 child/adolescent athletes 6–16 Damascus Syria; orofacial trauma prevalence + risk factors."),
    "42052228": ("screened_included", "I-pri", "high",
        "10-yr NEISS analysis 2015–2024 comparing HS vs collegiate softball injuries — direct §3.1 fit with AE-comparable data."),

    # --------------------- INCLUDES (medium confidence) ---------------------

    "11499758a_dup_check": ("screened_excluded", "R-other", "low",
        "(placeholder — ignore; tests dict integrity)"),  # removed below
    "16809595_v2": ("screened_excluded", "R-other", "low",
        "(placeholder — ignore; tests dict integrity)"),  # removed below

    # --------------------- EXCLUDES (high confidence) ---------------------

    "15562160": ("screened_excluded", "E-noprim", "high",
        "Perception/attitude survey of Nigerian athletes; outcome is psychological/sociological stress, no primary dental injury count per athlete-exposure (§3.1 'numerical data extractable' fails)."),
    "15773884": ("screened_excluded", "E-offtop", "high",
        "Cerebral palsy children dental trauma study; explicitly notes 'CP individuals do not take part in violent sport activities' — non-sport-related dental trauma (§3.2)."),
    "19055884": ("screened_excluded", "E-age", "high",
        "American Hockey League (AHL) — professional adult ice hockey players; outside 5–22 age range (§3.1)."),
    "19149336": ("screened_excluded", "E-offtop", "high",
        "Israel Defense Forces elite commando fighters — military setting, not sport-related (§3.1); participants adult."),
    "20711109": ("screened_excluded", "E-age", "high",
        "FC Barcelona professional soccer players — adult professionals, outside 5–22 (§3.1)."),
    "21496201": ("screened_excluded", "E-age", "high",
        "Brazilian Basketball Confederation Category A-1 adult athletes / national team — outside 5–22."),
    "29190193": ("screened_excluded", "E-offtop", "high",
        "Dogfighting injuries — animal subjects, off-topic (§3.1)."),
    "32134033": ("screened_excluded", "E-noprim", "high",
        "Awareness/knowledge survey of sports teachers; no athlete-level injury counts."),
    "33377302": ("screened_excluded", "E-age", "high",
        "Professional alpine ski racers worldwide; professional adults, outside 5–22."),
    "34257165": ("screened_excluded", "E-noprim", "high",
        "Editorial 'Revisiting Sports Dentistry' — no primary epidemiology data; review-type content."),
    "35802850": ("screened_excluded", "E-noprim", "high",
        "Knowledge survey of field hockey coaches — coaches, not athletes; no athlete-level injury counts."),
    "36479391": ("screened_excluded", "E-noprim", "high",
        "Awareness study of Libyan contact-sport coaches; no athlete-level injury counts."),
    "38729211": ("screened_excluded", "E-offtop", "high",
        "US Army Special Operations military working DOGS — animal subjects, off-topic."),
    "40267058": ("screened_excluded", "E-age", "high",
        "Adult Gaelic football athletes mouthguard compliance; population explicitly adult."),
    "40919643": ("screened_excluded", "E-noprim", "high",
        "Survey of German elite team SUPERVISORS — preventive knowledge of medical teams, not athlete-level injury counts."),
    "26545276": ("screened_excluded", "E-noprim", "high",
        "Clinical review article on splinting rationale for luxated/avulsed teeth — review content, no primary epidemiology."),
    "27875057": ("screened_excluded", "E-noprim", "high",
        "NATA Position Statement — clinical recommendations / consensus document, not primary epidemiologic data."),
    "23998194": ("screened_excluded", "E-offtop", "high",
        "Birth order as risk factor for dental trauma in 1282 Swiss children; non-sport-specific risk factor study, sport-related subset not the focus."),

    # --------------------- NEEDS HUMAN REVIEW ---------------------

    "11678537": ("needs_human_review", "R-data", "medium",
        "n=150 Ankara children TDI study; abstract does not isolate sport-related subset — confirm in full text whether sport-related counts are extractable."),
    "11766091": ("needs_human_review", "R-mixed", "medium",
        "n=250 patients ages 1–59 Brazil; sport = 3.6% of causes — full text needed to extract youth (5–22) subset."),
    "11880801": ("needs_human_review", "R-age", "medium",
        "Finland ice hockey 1991–1992 insurance dataset (n=479 injured); abstract does not state age distribution — likely includes youth + adult, full text needed."),
    "12017183": ("needs_human_review", "R-data", "medium",
        "Dicle University 1995–98 pediatric dental fractures; ages 9–11 peak. Sport-related subset not isolated in abstract — confirm in full text."),
    "12139268": ("needs_human_review", "R-mixed", "medium",
        "SE Queensland 1998 dental trauma survey, ages 1–64; 16–20 group reported as sport-related — youth subset extractable but needs full text."),
    "12154770": ("needs_human_review", "R-age", "medium",
        "Professional and semi-professional contact-sport athletes — age range not stated; full text needed to confirm any youth (5–22) data."),
    "12656848": ("needs_human_review", "R-data", "medium",
        "University of Jordan pediatric dentistry 1997–2000, ages 10–12 peak; sport-related etiology not isolated in abstract."),
    "15362317": ("needs_human_review", "R-data", "medium",
        "Australian Football Injury Prevention Project RCT; abstract reports MG compliance, not injury counts — full text may contain dental injury outcome data."),
    "15643760": ("needs_human_review", "R-data", "medium",
        "11–13 yr Brazilian schoolchildren; 'physical leisure activities' 28.9% but specific sport-related counts not isolated."),
    "15853840": ("needs_human_review", "R-data", "medium",
        "5th–6th grade Jerusalem schoolchildren n=1195; sport mentioned among reasons but not isolated as primary data."),
    "16711635": ("screened_excluded", "E-age", "high",
        "Ontario adults aged 18–50; majority outside 5–22 range; sport-related subset for 18–22 may be too small/unclear from abstract."),
    "16872385": ("needs_human_review", "R-data", "medium",
        "12-yr Brazilian schoolchildren TDI; abstract focuses on overjet risk factor — full text needed for sport-related subset counts."),
    "17194069": ("needs_human_review", "R-data", "medium",
        "n=2725 Thai children 11–13; sport-related subset not isolated in abstract."),
    "17227375": ("needs_human_review", "R-data", "medium",
        "Mouthguard effect on neurocognitive deficits after concussion; primary outcome is concussion neurocog, dental injury data may be secondary in full text."),
    "17511835": ("needs_human_review", "R-age", "medium",
        "Inline skating Switzerland + Germany; age range not in abstract — could be predominantly adult."),
    "17846669": ("needs_human_review", "R-age", "medium",
        "n=370 male enrollees National Cadet Corps India; age range not stated — NCC enrollees often 13–22, but needs verification."),
    "18173668": ("needs_human_review", "R-data", "medium",
        "Children's Hospital Buffalo pediatric dental trauma requiring fixation; sport-related subset not isolated in abstract."),
    "18352919": ("needs_human_review", "R-mixed", "medium",
        "Otago NZ 2000–2004 dental school, ages 2–86 peak 16–25; youth (5–22) subset overlaps but full text needed to extract."),
    "18721342": ("needs_human_review", "R-age", "medium",
        "China basketball players n=236, 77 professional; age range not stated."),
    "18821955": ("needs_human_review", "R-age", "medium",
        "Mountain biking Switzerland/Austria/Germany/Italy n=423 males; age range not in abstract."),
    "19021650": ("needs_human_review", "R-data", "medium",
        "Czech 90 avulsed permanent teeth in 58 children — youth fits, but sport-related subset not isolated in abstract."),
    "19021660": ("needs_human_review", "R-age", "medium",
        "Australian rural dental trauma — age range not stated in abstract excerpt."),
    "19615582": ("needs_human_review", "R-mixed", "medium",
        "n=273 facial fracture patients Switzerland — age range not stated, could include adults."),
    "20089070": ("needs_human_review", "R-data", "medium",
        "Yazd Iran 9–14 yr schoolchildren TDI; sport-related subset not isolated in abstract."),
    "20572841": ("needs_human_review", "R-age", "medium",
        "Pan American Games athletes 2007 — adult/elite athletes, likely mostly outside 5–22."),
    "20666978": ("needs_human_review", "R-data", "medium",
        "n=1612 11–14 yr Brazilian schoolchildren TDI; sport-related subset not isolated."),
    "20669600": ("needs_human_review", "R-age", "medium",
        "Hurling injuries Mid-Western Regional Hospital Limerick n=70; age range not stated."),
    "20946344": ("needs_human_review", "R-mixed", "medium",
        "n=384 patients ages 7–65, 66% children — youth subset extractable but full text needed."),
    "21063551": ("screened_included", "I-pri", "high",
        "PMC full-text confirms ages 18–25 (mean ~22). Within-scope: 18–22 subset = youth_primary; 23–25 subset = adult_comparator (decision 2026-05-22). Combat sports (boxing/taekwondo/kickboxing/Muay Thai). [Resolved via PMC2966561 full-text fetch, 2026-05-22.]"),
    "21199336": ("needs_human_review", "R-age", "medium",
        "Floorball Switzerland + Sweden n=608 (565 athletes + 43 coaches); age range not stated."),
    "21382033": ("screened_excluded", "E-age", "high",
        "PMC full-text confirms mean age 23 (no further age stratification visible) — population is predominantly adult, outside 5–22 scope. [Resolved via PMC9374803 full-text fetch, 2026-05-22.]"),
    "21755701": ("needs_human_review", "R-data", "medium",
        "Junior AND senior basketball players orofacial injuries; junior subset likely extractable but abstract does not give counts by group."),
    "21790975": ("needs_human_review", "R-data", "medium",
        "n=387 Brazilian adolescents 12–15; focus on 'non-accidental collision' — sport-related subset unclear."),
    "21880516": ("needs_human_review", "R-data", "medium",
        "n=502 schoolchildren 11–14 orthodontic risk factor study; sport involvement not in abstract."),
    "22107072": ("needs_human_review", "R-age", "medium",
        "Water polo Switzerland n=415 players from 6 divisions — likely mostly adult but youth subset may exist."),
    "22882839": ("needs_human_review", "R-age", "medium",
        "Para-Pan American Games athletes Rio — adults likely dominate; youth (16–22) subset may be present."),
    "23534038": ("needs_human_review", "R-data", "medium",
        "n=2560 12-yr Jordanian schoolchildren TDI; sport-related subset not isolated in abstract."),
    "24198704": ("included", "I-pri", "high",
        "FULL-TEXT REVIEWED 2026-06-12 (PMC3809047). Prospective injury surveillance of 6 women's national Shotokan karate championships, Iran, 2004-2005, all age groups (youth competitors present). 186 injuries / 1139 bouts / 1019 athletes; dental = tooth avulsion or subluxation (3, 1.6%). Sport-related dental count + youth ages present → meets §3.1/§3.3. Extracted as halabchi2007 (1 mixed-age pooled row; dental count not age-stratified)."),
    "24505897": ("needs_human_review", "R-data", "medium",
        "n=372 Romanian 8–20 yr; sport-related subset not isolated."),
    "25244279": ("needs_human_review", "R-data", "medium",
        "Samsun Turkey 2007–11 emergency dental trauma in children n=320; sport-related subset not isolated."),
    "25536987": ("needs_human_review", "R-age", "medium",
        "Zagreb amateur (n=60) + professional (n=135) basketball — adult-dominant likely; youth subset extractable only if amateurs include U18."),
    "25600092": ("needs_human_review", "R-mixed", "medium",
        "n=15941 Special Olympics athletes Europe/Eurasia — mixed ages (Special Olympics allows adults too); youth subset extractable."),
    "25721283": ("needs_human_review", "R-age", "medium",
        "Royal Dental Hospital Melbourne 2009–2012 emergency surveillance audit — age range not in abstract."),
    "26058666": ("needs_human_review", "R-age", "medium",
        "Rugby players Malaysia, aged 16+ — most likely adult, but 16–22 subset extractable."),
    "26542314": ("needs_human_review", "R-age", "medium",
        "Showjumping Switzerland/France/Germany n=608 — age range not in abstract."),
    "26545273": ("needs_human_review", "R-data", "medium",
        "HS athletes US mouthguard mandate review — may be policy overview without primary injury data; full text needed."),
    "26678302": ("needs_human_review", "R-age", "medium",
        "Swiss boxing clubs n=217 boxers; age range not in abstract."),
    "26939219": ("needs_human_review", "R-data", "medium",
        "Cameroon 12–13 schoolchildren incisor trauma n=2287; sport-related subset not isolated."),
    "27622524": ("needs_human_review", "R-age", "medium",
        "Team handball 'top athletes' n=542; age range not in abstract — likely senior."),
    "28160512": ("needs_human_review", "R-age", "medium",
        "Professional handball n=100; professional = adult likely."),
    "28969286": ("screened_included", "I-pri", "high",
        "PMC full-text confirms population is 10–17 yr adolescents (squarely within scope). Primary outcome is TDI prevalence with self-esteem comparison; sport activities are listed as a primary etiology. [Resolved via PMC5620908 full-text fetch, 2026-05-22.]"),
    "30156365": ("needs_human_review", "R-age", "medium",
        "Water polo n=347 players 2015–16 season; age range not in abstract."),
    "30431180": ("needs_human_review", "R-mixed", "medium",
        "Israeli Special Olympics 2016 — Special Olympics athletes mixed ages (8+ allowed); youth subset extractable."),
    "31994310": ("needs_human_review", "R-age", "medium",
        "Bern Switzerland judo n=382; age range not in abstract."),
    "33188561": ("needs_human_review", "R-age", "medium",
        "CrossFit practitioners online survey; population likely adult (self-selected practitioners)."),
    "33220143": ("needs_human_review", "R-age", "medium",
        "Elite cross-country mountain biking + field hockey athletes pre-Olympic competitions Rio; elite likely adult, but some youth elite athletes may be present."),
    "34047017": ("needs_human_review", "R-age", "medium",
        "Lorraine France handball n=>15 yr — primarily adult; 15–22 subset extractable."),
    "34343071": ("needs_human_review", "R-age", "medium",
        "Ice hockey n=169 online survey — age range not in abstract."),
    "36327493": ("needs_human_review", "R-age", "medium",
        "Australian sub-elite football (soccer) injury insurance 2018–2020 — age group breakdown reported but exact ranges not in abstract."),
    "36394781": ("screened_included", "I-pri", "high",
        "PMC full-text confirms n=106 children aged 9–16 (squarely within scope). Sport = Gaelic football (contact). Primary outcome is MG design adequacy, but the paper carries TDI prevalence data for the cohort as a §3.3 outcome. [Resolved via PMC9669524 full-text fetch, 2026-05-22.]"),
    "36538371": ("fulltext_excluded", "E-age", "high",
        "FULL-TEXT REVIEWED 2026-06-12 (Acta Odontol Scand, medicaljournalssweden.se). Finnish tertiary trauma-centre retrospective series 2013-2020 of ice-hockey facial fractures (n=66; 98.5% male; 37 mandible fractures, 18 associated dental injuries). Not age-stratified, adult-dominated; no isolable 5-22 subset (§3.1)."),
    "36922269": ("needs_human_review", "R-age", "medium",
        "Kabaddi players Delhi-NCR — age range not in abstract; likely mixed youth/adult."),
    "37055924": ("needs_human_review", "R-age", "medium",
        "Malaysian para-athletes n=61 — age range not in abstract."),
    "37341423": ("needs_human_review", "R-age", "medium",
        "Croatian soccer all leagues n=393 — age range not in abstract."),
    "37431232": ("needs_human_review", "R-age", "medium",
        "Australian non-professional football insurance 2018–2020; age categories reported but ranges unclear."),
    "37791703": ("needs_human_review", "R-age", "medium",
        "Ladies Gaelic football MG cost reduction; abstract truncated in our dump — Ladies GAA is adult, but youth subset may exist."),
    "39452438": ("screened_included", "I-pri", "high",
        "PMC full-text confirms n=142 amateur athletes ages 5–65; n=38 (27%) are under 18 (youth subset). Source qualifies for inclusion; per the 2026-05-22 decision, youth rows tagged youth_primary and adult rows tagged adult_comparator. [Resolved via PMC11505621 full-text fetch, 2026-05-22.]"),
    "39630092": ("needs_human_review", "R-age", "medium",
        "German elite athletes 18–35; 18–22 subset within scope but mixed-ages population."),
    "40662680": ("needs_human_review", "R-age", "low",
        "FULL TEXT RETRIEVED 2026-06-12 (Swiss Dental Journal 2025, Robbiani & Filippi). Swiss nationwide survey of Muay Thai/K-1/kickboxing martial artists (n=419 analysed). Reports dental injuries (52 cases, 19%, all-ages; 8.7% during competition) and MG use (75% any, 31.5% professional). STILL needs_human_review: subject age distribution is in a PDF table that did not extract cleanly (the readable strata are training-experience bands, not ages), so whether a 5-22 subset is present/separable could not be confirmed. Human read of the age table required before include/exclude."),
}

# Remove the placeholder dummy entries so they don't accidentally make it into the run.
MANUAL_DECISIONS.pop("11499758a_dup_check", None)
MANUAL_DECISIONS.pop("16809595_v2", None)


# ============================================================================
# 2026-05-23 — Journal-restricted search additions (PROTOCOL §4.2 supplementary)
# Searches in Dent Traumatol, Pediatr Dent, Am J Sports Med, Br J Sports Med,
# J Athl Train returned 132 NEW PMIDs (212 total, 80 already in the original
# PubMed seed). Decisions below are based on title + publication-type metadata
# only (and abstract excerpts where ambiguous).
# ============================================================================

MANUAL_DECISIONS.update({

    # --------- INCLUDES (clear from title) ---------

    "11798994": ("screened_included", "I-pri", "high",
        "Junior A hockey (youth tier, typically ages 16-21) — facial-protection vs head/neck/face injury comparison; sport-specific dental data likely."),
    "15245517": ("screened_excluded", "E-noprim", "high",
        "Nigerian DENTISTS' knowledge/attitudes about MG protection — dentist survey, no athlete-level injury data."),
    "15522054": ("screened_included", "I-pri", "high",
        "Cost-of-treatment study for children/adolescents with permanent incisor injuries — youth pop with primary dental injury data."),
    "18203866": ("screened_included", "I-pri", "high",
        "Collegiate (NE) rugby union prospective cohort — collegiate ages within 5-22, sport-specific injury data."),
    "18821952": ("screened_included", "I-pri", "high",
        "Root fractures in children and adolescents — diagnostic + epidemiology paper covering youth population."),
    "22051036": ("screened_included", "I-pri", "high",
        "Kick-scooters dental injuries in 6-12 yr children — perfect age + activity fit (recreational sport)."),
    "31937578": ("screened_included", "I-pri", "high",
        "Nested case-control of mouthguard use vs concussion in youth ice hockey (n=315 cases) — exactly the kind of study the protocol §3.3 wants."),
    "8883693": ("screened_included", "I-pri", "high",
        "Texas girls' high school basketball injury incidence — perfect §3.1 fit (HS = adolescent)."),
    "39417350": ("screened_included", "I-pri", "high",
        "Pediatric patients with proclined anterior teeth, stress distribution with/without MG — pediatric pop with mouthguard outcome."),

    # --------- INCLUDES (medium — likely youth subset extractable) ---------

    "12656867": ("needs_human_review", "R-age", "medium",
        "Team handball Switzerland+Germany dental trauma — age range not in title; could include youth amateur teams."),
    "12848712": ("needs_human_review", "R-age", "medium",
        "Basketball MG use Victoria Australia — age range not in title."),
    "12848713": ("screened_excluded", "E-noprim", "high",
        "Knowledge/attitudes survey of secondary school COACHES — coaches, not athletes; no athlete-level injury counts."),
    "15562172": ("fulltext_excluded", "E-age", "high",
        "FULL-TEXT REVIEWED 2026-06-12 (PMC1724969). Prospective ED maxillofacial-injury surveillance, Switzerland (750 maxillofacial injuries from 57,248 ED cases; 90 sport-related). Not age-stratified — no way to isolate a 5-22 subset (§3.1). Outcome is mid-face/mandibular fractures; dental (tooth) injuries not separately counted (§3.3)."),
    "16118304": ("fulltext_excluded", "E-age", "high",
        "FULL-TEXT REVIEWED 2026-06-12 (PMC1725322). NZ rugby union ecological study of the mouthguard mandate's effect on ACC dental-injury claims (2644 claims in 1995; 43% reduction by 2003; RR non-wearers vs wearers 4.6). Claims are national, all-ages ACC data not separable into a 5-22 band; no youth-scoped dental count extractable (§3.1). Rich MG context logged in decisions.md but not includable as a youth data point."),
    "16643287": ("needs_human_review", "R-age", "medium",
        "Ankara Turkey MG utilization rates — age range not in title."),
    "1982928": ("needs_human_review", "R-age", "medium",
        "Club rugby union players orofacial injuries — age unclear; club rugby often adult-only."),
    "23311956": ("needs_human_review", "R-age", "medium",
        "Swedish ice hockey MG/face guards attitudes part 2 — age range not in title."),
    "23374909": ("needs_human_review", "R-age", "medium",
        "Swedish ice hockey MG/face guards attitudes part 1 (methods) — age range not in title."),
    "24890132": ("needs_human_review", "R-age", "medium",
        "Rugby players Malaysia MG factors — likely adult; full text needed."),
    "27015854": ("needs_human_review", "R-age", "medium",
        "Dutch field hockey orodental injury patterns — age range not in title."),
    "2893649": ("fulltext_excluded", "E-age", "high",
        "FULL-TEXT REVIEWED 2026-06-12 (PMC1478470). International field hockey players, Netherlands; 20% sustained serious dental damage (women 16%, men 22%), MG used consistently by only 20%. No age data reported and 'international' = elite senior players; no identifiable 5-22 subset (§3.1)."),
    "2907269": ("needs_human_review", "R-age", "medium",
        "Comparison of maxillofacial+dental injuries in 4 contact team sports (1988) — age unclear."),
    "32794620": ("needs_human_review", "R-age", "medium",
        "Brazilian rugby union orofacial trauma + MG use — age range not in title."),
    "38084787": ("needs_human_review", "R-age", "medium",
        "Latin American field hockey ODESUR 2022 Games — ODESUR is multi-age regional games; need full text."),
    "19208022": ("needs_human_review", "R-age", "medium",
        "American football Turkey orofacial/dental protection — age range not in title."),
    "19302200": ("needs_human_review", "R-age", "medium",
        "University athletes Erzurum Turkey MG use — university age likely 18-22 (in scope) but needs confirmation."),
    "18254": ("needs_human_review", "R-age", "medium",
        "Rugby dental injury prevalence + MG attitudes (1977) — age range not in title."),
    "9566015": ("needs_human_review", "R-data", "medium",
        "Children's hospital dental trauma diagnosis/treatment — youth population, but sport-related subset unclear."),
    "16422751": ("screened_excluded", "E-age", "high",
        "Swiss PROFESSIONAL athletes orofacial/cerebral injuries — professional = adult, outside 5-22."),
    "26527674": ("screened_excluded", "E-age", "high",
        "UK PROFESSIONAL male football players oral health — adult professional pop, outside scope."),
    "18352922": ("needs_human_review", "R-age", "medium",
        "Elite female field hockey players orofacial injuries — elite usually adult but youth elite teams may be present."),
    "21047841": ("screened_excluded", "E-age", "high",
        "Dental service at 2008 Summer Olympics — elite adult Olympians, outside scope."),
    "23467963": ("screened_excluded", "E-age", "high",
        "London 2012 Olympic Village Polyclinic usage by athletes — elite adult Olympians."),
    "23902777": ("screened_excluded", "E-age", "high",
        "Paralympians injury study — elite adult Paralympians, outside scope."),
    "24068332": ("screened_excluded", "E-age", "high",
        "London 2012 Olympics oral health/performance — elite adult Olympians."),
    "2078799": ("screened_excluded", "E-age", "high",
        "International rugby players MG attitudes (1990) — international adult rugby."),
    "8242279": ("screened_excluded", "E-age", "high",
        "4 teams 2nd International Games (1993) — international elite adult."),
    "4027500": ("screened_excluded", "E-age", "high",
        "Rugby MG evaluation (1985) — adult rugby focus."),
    "4027501": ("screened_excluded", "E-age", "high",
        "1984 Wallabies (Australian elite rugby team) MG study — elite adult."),
    "6130812": ("needs_human_review", "R-age", "medium",
        "Rugby dental injuries + MG attitudes (1982) — age unclear."),
    "2638006": ("needs_human_review", "R-age", "medium",
        "Oral trauma in 'adolescent athletes' MG study (1989) — title suggests adolescent (in scope) but old paper, full text needed."),
    "2610287": ("screened_excluded", "E-age", "high",
        "1987 US Rugby Football tour players MG attitudes — elite adult rugby."),
    "2859903": ("screened_excluded", "E-age", "high",
        "1984 Great Britain Rugby League touring team — elite adult."),
    "3233461": ("screened_excluded", "E-age", "high",
        "1986 Australian Rugby League touring side — elite adult."),
    "34197681": ("screened_excluded", "E-offtop", "high",
        "Israeli military divers oral pathoses — military/occupational, not sport-related (§3.1)."),

    # --------- EXCLUDES — lab / methods / materials studies of mouthguards ---------

    "11273967": ("screened_excluded", "E-offtop", "high",
        "Scuba diving mouthpiece evaluation — not a sport dental injury study (scuba mouthpieces ≠ sport mouthguards in this context)."),
    "11477022": ("screened_excluded", "E-noprim", "high",
        "Lab study of projectile forces on mouthguards — no human injury epi data."),
    "12055116": ("screened_excluded", "E-noprim", "high",
        "EVA closed-cell foam material mechanics — pure lab/materials study."),
    "12656867": ("needs_human_review", "R-age", "medium",
        "Handball MG knowledge/prevention — age range unclear (overrides earlier duplicate-key entry above)."),
    "15970953": ("screened_excluded", "E-offtop", "high",
        "Smokeless tobacco intervention RCT — off-topic (tobacco cessation, not dental injury)."),
    "16558261": ("screened_excluded", "E-offtop", "high",
        "Charcot-Marie-Tooth syndrome (neurological disease) — off-topic, not dental injury or sport-related."),
    "16558367": ("screened_excluded", "E-offtop", "high",
        "1994 athletic training salaries — off-topic."),
    "16558422": ("screened_excluded", "E-offtop", "high",
        "Sports-related TMJ dysfunctions evaluation — TMJ ≠ dental injury per §3.3; orofacial without dental involvement."),
    "16872387": ("screened_excluded", "E-noprim", "high",
        "Lab comparison of forces through EVA mouthguards — materials study, no injury data."),
    "17000712": ("screened_excluded", "E-noprim", "high",
        "Palatal side MG design effect on wearability — lab/usability study."),
    "17597943": ("screened_excluded", "E-noprim", "high",
        "MG structural changes during HS football season — materials/durability, not injury data."),
    "1810619": ("screened_excluded", "E-noprim", "high",
        "Physiological effects of wearing MG (1991) — physiology, not injury epi."),
    "18173665": ("screened_excluded", "E-noprim", "high",
        "Vacuum technique for MG fabrication — manufacturing methods."),
    "18489486": ("screened_excluded", "E-noprim", "high",
        "MG anterior occlusion comparison — lab study, no injury data."),
    "18721344": ("screened_excluded", "E-noprim", "high",
        "Wearability + physiological effects RCT — usability/physiology, not injury epi."),
    "18821956": ("screened_excluded", "E-noprim", "high",
        "Pilsen primary school TEACHERS attitudes to dental trauma — teachers, not athlete injury data."),
    "19583574": ("screened_excluded", "E-noprim", "high",
        "Taekwondo MG strength/speed/anaerobic performance — physiology study, not injury epi."),
    "19583579": ("screened_excluded", "E-noprim", "high",
        "Knowledge of dental emergency procedures among sports participants — knowledge survey, no athlete injury count."),
    "19208013": ("needs_human_review", "R-data", "medium",
        "Boil-and-bite MG free distribution intervention in young adult amateurs — could have injury data; full text needed."),
    "19919541": ("screened_excluded", "E-offtop", "high",
        "Avulsed teeth treatment outcomes — clinical treatment study, not sport-related epi (sport subset unclear, abstract doesn't isolate)."),
    "20070349": ("screened_excluded", "E-noprim", "high",
        "Public school educator KNOWLEDGE of initial dental trauma mgmt — educators, no athlete injury data."),
    "20572840": ("screened_excluded", "E-noprim", "high",
        "TDI knowledge among present + prospective TEACHERS — teachers, not athletes."),
    "21635690": ("screened_excluded", "E-offtop", "high",
        "Quality of online MG info — meta-study of internet content, no epi."),
    "21854544": ("screened_excluded", "E-noprim", "high",
        "MG fabrication with hard insert + space — manufacturing/lab."),
    "22272945": ("screened_excluded", "E-noprim", "high",
        "Different MG types vs collegiate athlete strength/performance — physiology, not injury epi."),
    "22805585": ("screened_excluded", "E-noprim", "high",
        "MG shock absorption in two malocclusions (fiber Bragg grating) — lab/sensor study."),
    "24261712": ("screened_excluded", "E-noprim", "high",
        "Custom vs standard MG usability properties — usability, not injury epi."),
    "24597774": ("screened_excluded", "E-noprim", "high",
        "Sport-participant knowledge of dental emergencies + MG — knowledge survey."),
    "25264187": ("screened_excluded", "E-noprim", "high",
        "Custom vs standard MG comfort + subjective assessment — usability survey."),
    "25283822": ("screened_excluded", "E-noprim", "high",
        "MG design for spaced dentition — lab design study."),
    "26400727": ("screened_excluded", "E-noprim", "high",
        "Model inclination during MG fabrication — manufacturing study."),
    "26948149": ("screened_excluded", "E-noprim", "high",
        "Custom vs boil-and-bite MG comparison — lab evaluation."),
    "28231638": ("screened_excluded", "E-noprim", "high",
        "MG shock absorption comparison — lab study."),
    "29691290": ("screened_excluded", "E-noprim", "high",
        "Letter to editor about international athlete oral health (auto-handled by Letter pubtype; entry here for completeness)."),
    "29853456": ("screened_excluded", "E-noprim", "high",
        "Editorial (auto-handled by Editorial pubtype)."),
    "30295996": ("screened_excluded", "E-noprim", "high",
        "MG design retention/usability — lab/design study."),
    "30481393": ("screened_excluded", "E-noprim", "high",
        "MG palatal extension shortening RCT (water polo) — usability outcome only."),
    "31220414": ("screened_excluded", "E-noprim", "high",
        "MG vacuum forming model position study — lab fabrication."),
    "32058660": ("screened_excluded", "E-noprim", "high",
        "Water polo COACHES knowledge of dental injuries/emergencies — coaches, no athlete injury data."),
    "32220853": ("screened_excluded", "E-noprim", "high",
        "Editorial 'MGs should be worn in contact sports' (auto-handled)."),
    "32304262": ("screened_excluded", "E-noprim", "high",
        "Light-cured resin + glass fiber net MG material — lab/materials."),
    "32790959": ("screened_excluded", "E-noprim", "high",
        "Multi-society policy/position statement on sports dentistry — consensus/policy, no primary epi."),
    "33774914": ("screened_excluded", "E-noprim", "high",
        "Water polo COACHES attitudes to orofacial injury prevention — coaches, no athlete injury data."),
    "38234013": ("screened_excluded", "E-noprim", "high",
        "Custom vs boil-and-bite MG comfort RCT (basketball) — usability outcome only."),
    "38234017": ("screened_excluded", "E-noprim", "high",
        "Athletic TRAINERS knowledge of emergency dental mgmt — trainers, no athlete injury data."),
    "38738536": ("screened_excluded", "E-noprim", "high",
        "Editorial (auto-handled)."),
    "39318169": ("screened_excluded", "E-offtop", "high",
        "Quality of YouTube videos about MG — meta-study of online content."),
    "39384388": ("screened_excluded", "E-noprim", "high",
        "Editorial / FSEM position (auto-handled)."),
    "40065607": ("screened_excluded", "E-offtop", "high",
        "Custom MG for BRUXISM during physical activity — bruxism is not a sport injury; off-topic per §3.3."),
    "4014535": ("screened_excluded", "E-noprim", "high",
        "Comparison of athletic MG materials (1985) — lab/materials."),
    "40268332": ("screened_excluded", "E-noprim", "high",
        "FSEM infographic position statement — no primary data."),
    "40304186": ("screened_excluded", "E-offtop", "high",
        "Sport impacts on TMJ system (frontal impacts) — TMJ, not dental per §3.3."),
    "6102441": ("screened_excluded", "E-noprim", "high",
        "Editorial on prevention of dental injuries in sports (1980) — auto-handled."),
    "9006695": ("screened_excluded", "E-offtop", "high",
        "Intercondylar notch / ACL geometry — knee anatomy, not dental."),
    "9015601": ("screened_excluded", "E-offtop", "high",
        "British elite cyclists squad medical — not dental injury focus."),
    "9132205": ("screened_excluded", "E-offtop", "high",
        "Sports drinks hazard to teeth (case) — dental erosion from drinks, not injury (auto-handled by Case Reports)."),
    "9132208": ("screened_excluded", "E-noprim", "high",
        "Standard test procedure for MG assessment — methodology development."),
    "9298567": ("screened_excluded", "E-noprim", "high",
        "Comment/letter re: sports drinks and teeth — auto-handled."),
    "9429019": ("screened_excluded", "E-noprim", "high",
        "Comment/letter re: sports drinks and teeth — auto-handled."),
    "9442537": ("screened_excluded", "E-noprim", "high",
        "Parental attitudes toward MG (1998) — attitude survey, no injury data."),
    "39829203": ("screened_excluded", "E-offtop", "high",
        "Re-injury anxiety instrument validation — psychological measure, not injury epi."),
    "3812864": ("screened_excluded", "E-offtop", "high",
        "Recurrent herpes labialis in skiers + sunscreen — infectious/dermatology, not dental injury."),
    "3620800": ("screened_excluded", "E-noprim", "high",
        "Modified maxillary mouthguard design (1987) — lab/design."),

    # --------- Auto-handled (review / case / lang) — explicit entries for clarity ---------

    "10786868": ("screened_excluded", "E-case", "high",
        "von Willebrand's disease case report — auto-handled by Case Reports pubtype."),
    "12453835": ("screened_excluded", "E-review", "high",
        "Historical review of ice hockey head/neck injury avoidability — auto-handled."),
    "15849286": ("screened_excluded", "E-review", "high",
        "Review of craniomaxillofacial injury prevention research — auto-handled."),
    "15849291": ("screened_excluded", "E-review", "high",
        "Review of sports MG protection/types — auto-handled."),
    "15970958": ("screened_excluded", "E-case", "high",
        "HS soccer goalkeeper maxillofacial+dental case — single case (auto via Case Reports if tagged; else single-case exclusion §3.2)."),
    "17984193": ("screened_excluded", "E-review", "high",
        "Review of growth factor delivery in sports injuries — off-topic + review (auto-handled)."),
    "1810620": ("screened_excluded", "E-case", "high",
        "Waterbike injuries case report — auto-handled."),
    "18821961": ("screened_excluded", "E-case", "high",
        "Lateral luxation from long-term boxing — case report (auto-handled)."),
    "20070350": ("screened_excluded", "E-case", "high",
        "Crown fragment reattachment case — auto-handled."),
    "22676323": ("screened_excluded", "E-case", "high",
        "Crown reattachment with chisel-type fracture case — auto-handled."),
    "23511697": ("screened_excluded", "E-review", "high",
        "Sports injury prevention apps review — auto-handled."),
    "24910176": ("screened_excluded", "E-case", "high",
        "Cone-beam CT of horizontal root fracture case — auto-handled."),
    "25263651": ("screened_excluded", "E-review", "high",
        "Review of oral health + elite sport performance — auto-handled."),
    "26511002": ("screened_excluded", "E-review", "high",
        "Systematic review of dentofacial trauma + MG in field hockey — auto-handled; mine for primary sources."),
    "28376278": ("screened_excluded", "E-case", "high",
        "Dental trauma prevention with MG in a nose-fracturing blow — case report (auto-handled)."),
    "28965361": ("screened_excluded", "E-review", "high",
        "1st International Sports Dentistry Workshop MG report — review/consensus (auto-handled)."),
    "29554460": ("screened_excluded", "E-review", "high",
        "Systematic review of mesenchymal stem cell protocols — off-topic + review (auto-handled)."),
    "32176431": ("screened_excluded", "E-review", "high",
        "SR+MA of dentofacial injury prevalence in contact sports — auto-handled; mine for primary sources."),
    "32790910": ("screened_excluded", "E-review", "high",
        "Scoping review of extrinsic factors in orofacial sport trauma — review (auto-handled)."),
    "33220152": ("screened_excluded", "E-review", "high",
        "SR of knowledge re: emergency mgmt of TDI in sports — auto-handled."),
    "34019343": ("screened_excluded", "E-review", "high",
        "Review of MG recommendations for dentists — auto-handled."),
    "36436198": ("screened_excluded", "E-review", "high",
        "Sports MG materials/fabrication/standards review — auto-handled."),
    "37367210": ("screened_excluded", "E-review", "high",
        "Suggested universal dental exam protocol in sports — review/consensus (auto-handled)."),
    "40019130": ("screened_excluded", "E-review", "high",
        "Digital workflow for carbon fiber face guard (case + review) — auto-handled."),
    "6614299": ("screened_excluded", "E-case", "high",
        "Impacted 3rd molars + mandibular fractures (case) — auto-handled."),

})


# ============================================================================
# 2026-05-24 — Second journal-restricted batch (J Endod, J OMFS, Pediatrics,
# Inj Prev, Orthop J Sports Med). 104 new PMIDs; auto-rules cleared 14 of 104.
# Below are decisions for the remaining 90 (mostly E-offtop or E-age — these
# journals carry a lot of surgical / non-dental papers).
# ============================================================================

MANUAL_DECISIONS.update({
    # --- INCLUDES from the batch ---
    "11003192": ("screened_included", "I-pri", "high",
        "Baseball face guards RCT in receptive youth league — youth + sport + protective equipment + acceptability outcome."),
    "15178672": ("screened_included", "I-pri", "high",
        "Parental perceptions of mandatory MG in competitive YOUTH soccer — directly relevant §3.3."),
    "16081755": ("screened_included", "I-pri", "high",
        "Custom-fitted MG in football RCT — likely collegiate or HS."),
    "18519488": ("screened_included", "I-pri", "high",
        "HS baseball injuries 2005-2007 (RIO) epi — perfect §3.1 fit."),
    "22260909": ("screened_included", "I-pri", "high",
        "Dental injuries in pediatric facial fracture patients — youth, dental + orofacial."),
    "24813778": ("screened_included", "I-pri", "high",
        "ED visits with facial fractures among children + adolescents — population-level pediatric epi."),
    "32866487": ("screened_included", "I-pri", "high",
        "Sports-related OMF injuries 5-yr retrospective Pusan National University — surveillance epi."),
    "33614796": ("screened_included", "I-pri", "high",
        "ED visits for head injuries in youth non-tackle football 2014-2018 — perfect §3.1 fit."),
    "34973164": ("screened_included", "I-pri", "high",
        "2,845 head & neck injuries across various martial arts — relevant; large surveillance dataset."),
    "35340727": ("screened_included", "I-pri", "high",
        "Maxillofacial injuries NCAA Division I athletes 13 sports — collegiate + sport-specific, large dataset."),
    "8784371":  ("screened_included", "I-pri", "high",
        "Little League baseball survey — youth baseball epi."),
    "9191640":  ("screened_included", "I-pri", "high",
        "Sport-related mandibular fractures retrospective — mandible includes dental adjacency."),

    # --- needs_human_review (interesting but full-text needed) ---
    "20493614": ("needs_human_review", "R-data", "medium",
        "Piracicaba 9-yr dental trauma study — sport subset not isolated in title."),
    "25416466": ("needs_human_review", "R-data", "medium",
        "BokSmart rugby intervention South Africa — may have injury counts; need full text."),
    "31884077": ("needs_human_review", "R-age", "medium",
        "American professional sports leagues craniomaxillofacial — predominantly adult; check if youth subset reported."),
    "39060115": ("fulltext_excluded", "E-nodent", "high",
        "FULL-TEXT REVIEWED 2026-06-12 (Leeds Beckett repository PDF, Injury Prevention 2024). Cross-sectional study of sport-related (brain) concussion symptom non-reporting in UK community rugby league. 'Toothache' appears only as a sham symptom-checklist item and 'mouthguard' only as iMG sensor technology — no dental/orofacial injury outcome (§3.3)."),
    "41087084": ("needs_human_review", "R-age", "medium",
        "Australian community rugby union concussion management — adult-leaning."),
    "19925982": ("fulltext_excluded", "E-offtop", "high",
        "FULL-TEXT REVIEWED 2026-06-12 (PMC2782766). LA County adolescents 14-20 (n=67) treated for orofacial injury at two trauma centres; aetiology 59% assault, 29% MVC/other, 9% gunshot, only 3% sport. Sport-related fraction (~2 cases) has no sport-specific breakdown → not sport-focused and no extractable sport dental data (§3.1 Setting / §3.3)."),

    # --- EXCLUDES — off-topic (mostly OMFS/OJSM surgical or non-dental) ---
    "10728540": ("screened_excluded", "E-offtop", "high", "Toughened glassware in bars — non-sport, off-topic."),
    "11331714": ("screened_excluded", "E-offtop", "high", "Scooter injuries — off-topic (off-protocol)."),
    "11770650": ("screened_excluded", "E-offtop", "high", "Tooth fairy + Santa drinking driver — not epi."),
    "12236313": ("screened_excluded", "E-noprim", "high", "Sports Dentistry for Endodontists — narrative/review style."),
    "12524610": ("screened_excluded", "E-offtop", "high", "Maxillofacial fractures 5-yr 237 patients — mixed adult, sport not isolated; OMFS clinical."),
    "15805433": ("screened_excluded", "E-offtop", "high", "'Winning, losing, and violence' — not epi."),
    "16360858": ("screened_excluded", "E-offtop", "high", "Zygomatico-orbital + zygomatic arch fractures Sao Paulo — adult OMFS."),
    "17307593": ("screened_excluded", "E-offtop", "high", "Isolated zygomatic arch fractures — adult OMFS clinical."),
    "19022127": ("screened_excluded", "E-offtop", "high", "Symptomatic pericoronitis QoL — off-topic."),
    "20079962": ("screened_excluded", "E-offtop", "high", "Associated injuries in facial fracture patients — adult OMFS."),
    "20116698": ("screened_excluded", "E-offtop", "high", "Facial trauma in ski/snowboarding — adult-leaning, no dental focus."),
    "20171484": ("screened_excluded", "E-offtop", "high", "Mandibular angle fracture operative complications — adult surgical."),
    "21665343": ("screened_excluded", "E-offtop", "high", "Stainless steel mesh in mandibular fractures — adult surgical."),
    "21665346": ("screened_excluded", "E-offtop", "high", "Motorcycle vs bicycle accidents OMF trauma — non-sport."),
    "22152627": ("screened_excluded", "E-offtop", "high", "Pulp exposure in mice — animal."),
    "23322260": ("screened_excluded", "E-offtop", "high", "Homicide risk Tanzania — off-topic."),
    "25511965": ("screened_excluded", "E-offtop", "high", "Stair ascent/descent osteocutaneous transfer — off-topic surgical."),
    "25914133": ("screened_excluded", "E-offtop", "high", "Inferior alveolar nerve injury — adult surgical."),
    "27597403": ("screened_excluded", "E-offtop", "high", "ICD-10 trauma mortality scoring system — off-topic methodology."),
    "28695139": ("screened_excluded", "E-offtop", "high", "Rugby shoulder dislocation video analysis — shoulder, not dental."),
    "29336880": ("screened_excluded", "E-offtop", "high", "Calcium silicate/glass ionomer marginal gaps — off-topic materials."),
    "30937322": ("screened_excluded", "E-offtop", "high", "Graft length ACL — off-topic ortho."),
    "31108061": ("screened_excluded", "E-offtop", "high", "Helmets bicycle maxillofacial — cycling not in §6.1 vocab; adult-leaning."),
    "31454504": ("screened_excluded", "E-offtop", "high", "E-scooter craniofacial injuries — non-sport-org."),
    "31696130": ("screened_excluded", "E-offtop", "high", "Distal humerus osteotomy capitellum — off-topic."),
    "31838092": ("screened_excluded", "E-offtop", "high", "Bikeshare programs maxillofacial — non-sport-org."),
    "31915268": ("screened_excluded", "E-offtop", "high", "GBD facial fractures epidemiology — global aggregate, no youth-sport focus."),
    "31915273": ("screened_excluded", "E-offtop", "high", "Burden of injury Socio-demographic Index — off-topic methodology."),
    "32008990": ("screened_excluded", "E-offtop", "high", "Kinesio taping after third molar — off-topic."),
    "32151652": ("screened_excluded", "E-offtop", "high", "Third molar impaction + condylar fractures — adult, not sport."),
    "32332142": ("screened_excluded", "E-offtop", "high", "Global injury morbidity GBD — off-topic methodology."),
    "32839249": ("screened_excluded", "E-offtop", "high", "GBD injuries methods — off-topic methodology."),
    "32953922": ("screened_excluded", "E-offtop", "high", "Subjective return to sports after ACL — off-topic ortho."),
    "32995346": ("screened_excluded", "E-offtop", "high", "Fifth metatarsal anatomy — off-topic."),
    "33015213": ("screened_excluded", "E-offtop", "high", "UCL elbow morphology — off-topic."),
    "33244476": ("screened_excluded", "E-offtop", "high", "Psychological readiness ACL — off-topic."),
    "33354581": ("screened_excluded", "E-offtop", "high", "Sonographic anchor placement ankle — off-topic."),
    "33553456": ("screened_excluded", "E-offtop", "high", "Anterolateral acromion morphology — off-topic."),
    "33607010": ("screened_excluded", "E-age", "high", "NHL face shields — professional adult hockey."),
    "34541011": ("screened_excluded", "E-offtop", "high", "Third/fourth digits flexor — off-topic."),
    "34568508": ("screened_excluded", "E-offtop", "high", "Demineralized bone matrix MSC PRP — off-topic."),
    "35464903": ("screened_excluded", "E-review", "high", "Scoping review of ice hockey injuries — review, use for source mining."),
    "35533718": ("screened_excluded", "E-offtop", "high", "Maxillofacial fractures in bicycle accidents — non-sport."),
    "35601732": ("screened_excluded", "E-offtop", "high", "Synovial MSCs chronic patients — off-topic."),
    "35958291": ("screened_excluded", "E-offtop", "high", "Anterior talofibular ligament — off-topic ankle."),
    "35964697": ("screened_excluded", "E-offtop", "high", "Geriatric craniomaxillofacial fractures — adult/geriatric."),
    "36199825": ("screened_excluded", "E-offtop", "high", "Opening-wedge HTO knee — off-topic ortho."),
    "36250031": ("screened_excluded", "E-offtop", "high", "Lateral ankle instability tendon allograft — off-topic."),
    "36368911": ("screened_excluded", "E-offtop", "high", "Parental parenting RCT for unintentional childhood injury — not sport-dental specific."),
    "36874048": ("screened_excluded", "E-offtop", "high", "Ballet foot/ankle injuries — off-topic adult professional."),
    "37123994": ("screened_excluded", "E-offtop", "high", "Infrapatellar fat pad fibrosis ACL — off-topic."),
    "37213661": ("screened_excluded", "E-offtop", "high", "Subchondroplasty bone marrow lesion knee — off-topic."),
    "37693805": ("screened_excluded", "E-offtop", "high", "Older age preop quadriceps strength — off-topic."),
    "37743043": ("screened_excluded", "E-offtop", "high", "Zygomaticomaxillary complex fractures — adult OMFS."),
    "37788800": ("screened_excluded", "E-age", "high", "NBA facial injuries — adult professional."),
    "38274016": ("screened_excluded", "E-offtop", "high", "Brostrom-Gould knot techniques — off-topic."),
    "38811153": ("screened_excluded", "E-offtop", "high", "Road traffic injury Bangladesh — off-topic."),
    "39143984": ("screened_excluded", "E-offtop", "high", "Foot/ankle MRI asymptomatic ballet — off-topic."),
    "39143987": ("screened_excluded", "E-offtop", "high", "KOJI AWARENESS running injuries — off-topic."),
    "39157590": ("screened_excluded", "E-offtop", "high", "ACL reconstruction PRO — off-topic."),
    "39832883": ("screened_excluded", "E-offtop", "high", "Computer vision rugby head-on-head — methodology."),
    "40575799": ("screened_excluded", "E-offtop", "high", "Preop pivot-shift / ramp lesions ACL — off-topic."),
    "40771885": ("screened_excluded", "E-offtop", "high", "Tibial osteotomy recurvatum — off-topic."),
    "40876806": ("screened_excluded", "E-offtop", "high", "Kinesio tape after 3rd molar extraction — off-topic."),
    "40935598": ("screened_excluded", "E-offtop", "high", "COVID school closures pediatric fracture — off-topic."),
    "41798103": ("screened_excluded", "E-offtop", "high", "Tendon allografting Achilles — off-topic."),
    "7862484":  ("screened_excluded", "E-offtop", "high", "Hockey helmets + injurious behavior — abstract too short to determine epi."),
    "8189291":  ("screened_excluded", "E-offtop", "high", "Nutritional status OMF malignancies — off-topic."),
    "9338836":  ("screened_excluded", "E-offtop", "high", "Medically attended injuries young children (1964 biography) — historical."),
    "9338837":  ("screened_excluded", "E-offtop", "high", "Rockland County Child Injury Project — older, broad."),
    "9666364":  ("screened_excluded", "E-offtop", "high", "Trends in injury mortality Taiwan 1965-94 — too broad."),
    "9666366":  ("screened_excluded", "E-offtop", "high", "Bicycle injury British Columbia — cycling not in §6.1."),
})
