"""AI-assisted screening decisions for the 200 PubMed candidates seeded 2026-05-21.

Each entry is keyed by PMID and produces a tuple of
(decision, reason_code, confidence, note).

These decisions were made by reading title + abstract + publication-type
metadata only. They are NOT a substitute for full-text review by the project
lead. Specifically:
  - 'screened_included' here means the abstract suggests the source meets
    PROTOCOL §3.1–3.3 criteria; the source still goes through full-text review.
  - 'screened_excluded' is a confident exclusion based on the abstract.
  - 'needs_human_review' flags abstracts where a key inclusion attribute
    (age range, sport-related subset, primary numerical data) could not be
    confirmed from the abstract alone.

The 44 automatic exclusions (non-English, Case Reports, Reviews/SR/MA) are
handled by 02_screen_candidates.py's auto rules and do not appear here.

Confidence levels:
  high   — abstract clearly supports the decision; further review unlikely to change it
  medium — abstract supports the decision but a full-text reader could plausibly disagree
  low    — used only for needs_human_review where the abstract is genuinely ambiguous
"""

MANUAL_DECISIONS: dict[str, tuple[str, str, str, str]] = {

    # --------------------- INCLUDES (high confidence) ---------------------

    "11202877": ("screened_included", "I-pri", "high",
        "Schoolchildren n=2022, sport-related causes ~30% of TDI; primary epidemiology data, age range consistent with 5–18."),
    "11499758": ("screened_included", "I-pri", "high",
        "Children 7–14 (88% of 590-child cohort); sports listed as etiology with frequency rank; primary data extractable for sport subset."),
    "11678540": ("screened_included", "I-pri", "high",
        "n=652 13-year-old adolescents Brazil; sport-related = 2.3% of TDI etiology; meets §3.1 age + sport + numerical data."),
    "11782645": ("screened_included", "I-pri", "high",
        "Prospective study of 50 NCAA Div I men's college basketball teams; reports dental injury rates/1000 AE with mouthguard effect — gold-standard fit (sport=basketball, age=collegiate, primary AE-denominator data)."),
    "14708646": ("screened_included", "I-pri", "high",
        "n=943 young adults ages 18–19 Israel; sport-specific dental injury counts (soccer, basketball) + mouthguard awareness — perfect §3.1 fit."),
    "15022997": ("screened_included", "I-pri", "high",
        "Norwegian children 7–18, n=1275 injured individuals; sport = 8% of dental injury etiology; primary data extractable."),
    "15592602": ("screened_included", "I-pri", "high",
        "Punahou School longitudinal 1988–2003 intermediate+HS athletes; dental injury rates/1000 athlete-sessions by sport — directly extractable AE-denominator data."),
    "15660753": ("screened_included", "I-pri", "high",
        "Turkish Premier Ice Hockey League youth AND adult players — youth subset is extractable per the abstract's explicit framing."),
    "15876321": ("screened_included", "I-pri", "high",
        "20-year experience of dental services at Central American & Caribbean Games; sport-related orofacial injuries reported across multiple sports."),
    "16162986": ("screened_included", "I-pri", "high",
        "Multicenter cluster-RCT, varsity football and rugby teams, mouthguard vs mouthguard, concussion + dental trauma outcomes per playing season — high-quality primary data."),
    "16809595": ("screened_included", "I-pri", "high",
        "Brazilian adolescents 14–15 n=1302 multilevel study; dental injury as outcome — likely sport-related subset extractable from full text."),
    "17073918": ("screened_included", "I-pri", "high",
        "Pony/horseback riding children, n=214; sport-specific dental trauma prevalence reported."),
    "17635356": ("screened_included", "I-pri", "high",
        "Glasgow pediatric dental trauma audit; abstract reports 79% of sporting-related injuries were in males — sport-specific data extractable."),
    "17670881": ("screened_included", "I-pri", "high",
        "USC intercollegiate athletes 1996–2005, n=51 dental injuries with sport-level detail; college = within 18–22 age range."),
    "17991235": ("screened_included", "I-pri", "high",
        "n=427 young adults ages 18–21 Israel; sport-specific dental injury counts + mouthguard data."),
    "18410389": ("screened_included", "I-pri", "high",
        "Population-based case-comparison study of n=2422 Ontario schoolchildren ages 12 and 14; primary etiology data."),
    "18689347": ("screened_included", "I-pri", "high",
        "Schoolchildren 10–14 Maseru Lesotho; permanent incisor TDI prevalence and etiology."),
    "18721348": ("screened_included", "I-pri", "high",
        "5th–6th grade Arab schoolchildren Jerusalem n=453; TDI prevalence + etiology."),
    "18821957": ("screened_included", "I-pri", "high",
        "n=2570 Ankara schoolchildren ages 7–9 and 11–13; specifically studies the role of sport in crown fractures."),
    "19030141": ("screened_included", "I-pri", "high",
        "RIO surveillance HS athletes 2005/06 and 2006/07; dental injuries are one of the RIC categories reported."),
    "19208012": ("screened_included", "I-pri", "high",
        "Random sample of n=6312 Taiwanese 15–18 yr senior HS students; TDI prevalence + activity-related etiology."),
    "19290905": ("screened_included", "I-pri", "high",
        "Random cluster sample of n=2610 South African 11–13 schoolchildren; TDI prevalence."),
    "19566982": ("screened_included", "I-pri", "high",
        "n=411 schoolboy cricketers at 8 private schools England + Australia; head/face/dental prevalence by country — strong sport+age fit."),
    "19614738": ("screened_included", "I-pri", "high",
        "NEISS analysis 1990–2003 of dental injuries to children 0–17; consumer products + activities including sport — primary surveillance dataset."),
    "20486946": ("screened_included", "I-pri", "high",
        "Snowboarders Turkey n=86; framed as 'adolescent and young adult' — within 5–22 envelope."),
    "21197817": ("screened_included", "I-pri", "high",
        "NZ ACC sports-related dental insurance claims 1999–2008; ~25–31k claims/year with age/sex/region/sport breakdown — large-scale surveillance, youth subset extractable."),
    "21299945": ("screened_included", "I-pri", "high",
        "Cork University Dental School pediatric trauma audit; cause and prevalence by type — primary clinical data."),
    "21457187": ("screened_included", "I-pri", "high",
        "Dunedin NZ children 0–10 orofacial trauma audit; sport contributes to causes in older subgroup."),
    "22976571": ("screened_included", "I-pri", "high",
        "Targu Mures retrospective study, ages 1–18, with physical-activity risk factor — youth-specific TDI data."),
    "23045787": ("screened_included", "I-pri", "high",
        "n=1111 Irish children ages 9–13; mouthguard use + dental trauma in sport — directly addresses §3.3."),
    "23532813": ("screened_included", "I-pri", "high",
        "Pediatric handball players Istanbul amateur national league; TDI frequency + mouthguard knowledge — sport + youth fit."),
    "25500920": ("screened_included", "I-pri", "high",
        "Cross-sectional athletes 12–22 in central India contact vs noncontact; mouthguard awareness + injury rates — perfect §3.1 age + sport fit."),
    "25520762": ("screened_included", "I-pri", "high",
        "n=cross-sectional HS students 8–16 in North India organized sports teams; sport-related orodental injury prevalence."),
    "25881567": ("screened_included", "I-pri", "high",
        "n=494 junior rugby league players + coaches Gold Coast; knowledge + TDI experience — junior population fits."),
    "26093006": ("screened_included", "I-pri", "high",
        "Collegiate women's field hockey head/face/eye injury epidemiology; college age within 18–22 — direct sport+age fit."),
    "26408377": ("screened_included", "I-pri", "high",
        "National HS Sports-Related Injury Surveillance Study 2008/09–2013/14; n=222 dental injuries with AE-denominator data per sport — gold-standard."),
    "27452795": ("screened_included", "I-pri", "high",
        "Japan junior HS + HS school sports clubs dental injury risk by sport; school-age population (mostly 12–18)."),
    "28054391": ("screened_included", "I-pri", "high",
        "Prospective cohort study of organized football in 7–12 yr children across 4 European countries; head/neck injuries documented — age fit + sport-specific."),
    "29284466": ("screened_included", "I-pri", "high",
        "School-aged athletes Miyagi prefecture Japan; sports-related dental injury prevalence + risk factors — explicit §3.3 outcome."),
    "29403232": ("screened_included", "I-pri", "high",
        "n=450 children 6–16 New Delhi; dental injury prevalence during sport + mouthguard awareness — direct fit."),
    "29406619": ("screened_included", "I-pri", "high",
        "Hockey Alberta surveillance 2001–2016 'all ages'; rates + mechanisms — youth subset extractable from governing-body dataset."),
    "29526055": ("screened_included", "I-pri", "high",
        "n=229 young athletes 4 contact sports (water polo/karate/taekwondo/handball); sport-related dental injury + mouthguard."),
    "30865370": ("screened_included", "I-pri", "high",
        "Amateur soccer players 7–18 Kuwait; TDI prevalence/type/causes — perfect age + sport fit."),
    "31179757": ("screened_included", "I-pri", "high",
        "NEISS pediatric sports/recreation dental injuries treated in US EDs — large-scale surveillance, exactly the kind of source PROTOCOL §4.1 targets."),
    "31228311": ("screened_included", "I-pri", "high",
        "n=2055 16-yr-old Norwegian pupils retrospective longitudinal TDI; life-course risk factors."),
    "31506903": ("screened_included", "I-pri", "high",
        "NZ ACC rugby injury claims 2005–2017 ages 5–40 with differences by age — large surveillance, youth subset (5–22) directly extractable."),
    "31624810": ("screened_included", "I-pri", "high",
        "Lithuanian 11–13 schoolchildren with focus on contact-sport mouthguard use; TDI prevalence + sport-specific data."),
    "31765062": ("screened_included", "I-pri", "high",
        "n=325 Catalonia field hockey players 'all age categories' incl. women; sport-specific orofacial injury + mouthguard data."),
    "33292522": ("screened_included", "I-pri", "high",
        "Children 6–13 Hamadan Iran sports-related dental injury study (random forest); primary data on athletes."),
    "33654038": ("screened_included", "I-pri", "high",
        "10-yr NEISS retrospective cohort of basketball-related craniofacial injuries; on-court management focus but primary epi data available."),
    "33710051": ("screened_included", "I-pri", "high",
        "n=682 NCAA Division I college athletes Columbia; dento-facial injury + concussion + mouthguard — college fits."),
    "33710063": ("screened_included", "I-pri", "high",
        "10-yr NEISS amateur ice hockey craniofacial injuries; explicit youth/amateur/professional breakdown — youth subset extractable."),
    "33741876": ("screened_included", "I-pri", "high",
        "10-yr NEISS soccer craniofacial injuries with demographic stratification — youth subset extractable."),
    "33746633": ("screened_included", "I-pri", "high",
        "n=7902 12- and 15-yr-old Lebanese schoolchildren national TDI study — large sample, perfect age fit."),
    "33848349": ("screened_included", "I-pri", "high",
        "Prospective cohort 9 Canadian pediatric EDs, ages 5–18 with sport-related concussion + mouthguard outcomes — direct §3.3 fit."),
    "34643329": ("screened_included", "I-pri", "high",
        "Cross-sectional observational cohort 9–16 yr Gaelic football children + parents; MG knowledge + dental trauma."),
    "34879017": ("screened_included", "I-pri", "high",
        "NEISS baseball craniofacial injuries youth (5–19) — perfect §3.1 age + sport fit, primary surveillance dataset."),
    "36317716": ("screened_included", "I-pri", "high",
        "National HS Sports-Related Injury Surveillance Study 2005/06–2019/20; dental injury counts + AE + mouthguard utilization — directly extractable."),
    "36428271": ("screened_included", "I-pri", "high",
        "n=7684 Japan school dental injury cases over 15 years across 5 sports — large governing-body surveillance dataset."),
    "36929194": ("screened_included", "I-pri", "high",
        "Japan school head injuries from tooth contact 2012–2018; school-age population by definition; primary count data."),
    "37743045": ("screened_included", "I-pri", "high",
        "NEISS retrospective 2003–2022 soccer craniomaxillofacial injuries; demographic stratification — youth subset extractable."),
    "37818921": ("screened_included", "I-pri", "high",
        "NEISS basketball dental injury mechanisms 2003–2022; primary mechanism data."),
    "38131151": ("screened_included", "I-pri", "high",
        "n=1340 adolescent contact-sport players Colombo Sri Lanka; oro-dental trauma burden + mouthguard usage — perfect §3.1 fit."),
    "39297708": ("screened_included", "I-pri", "high",
        "Sydney tertiary hospital 2001–2021 avulsion cohort, median age 12 (IQR 9–17); non-organized sport = most common cause — youth + sport fit."),
    "40655786": ("screened_included", "I-pri", "high",
        "Retrospective 100-case sports-related dental trauma study with focus on children/adolescents and contact sports."),
    "40771058": ("screened_included", "I-pri", "high",
        "n=125 youth basketball players Turkey 2024–25 season; TDI prevalence + mouthguard knowledge — direct §3.1 fit."),
    "40917008": ("screened_included", "I-pri", "high",
        "n=582 Syrian child athletes 6–16; orofacial-dental trauma prevalence + injury patterns + protective gear — direct §3.1 fit."),
    "41501720": ("screened_included", "I-pri", "high",
        "n=445 child/adolescent athletes 6–16 Damascus Syria; orofacial trauma prevalence + risk factors."),
    "42052228": ("screened_included", "I-pri", "high",
        "10-yr NEISS analysis 2015–2024 comparing HS vs collegiate softball injuries — direct §3.1 fit with AE-comparable data."),

    # --------------------- INCLUDES (medium confidence) ---------------------

    "11499758a_dup_check": ("screened_excluded", "R-other", "low",
        "(placeholder — ignore; tests dict integrity)"),  # removed below
    "16809595_v2": ("screened_excluded", "R-other", "low",
        "(placeholder — ignore; tests dict integrity)"),  # removed below

    # --------------------- EXCLUDES (high confidence) ---------------------

    "15562160": ("screened_excluded", "E-noprim", "high",
        "Perception/attitude survey of Nigerian athletes; outcome is psychological/sociological stress, no primary dental injury count per athlete-exposure (§3.1 'numerical data extractable' fails)."),
    "15773884": ("screened_excluded", "E-offtop", "high",
        "Cerebral palsy children dental trauma study; explicitly notes 'CP individuals do not take part in violent sport activities' — non-sport-related dental trauma (§3.2)."),
    "19055884": ("screened_excluded", "E-age", "high",
        "American Hockey League (AHL) — professional adult ice hockey players; outside 5–22 age range (§3.1)."),
    "19149336": ("screened_excluded", "E-offtop", "high",
        "Israel Defense Forces elite commando fighters — military setting, not sport-related (§3.1); participants adult."),
    "20711109": ("screened_excluded", "E-age", "high",
        "FC Barcelona professional soccer players — adult professionals, outside 5–22 (§3.1)."),
    "21496201": ("screened_excluded", "E-age", "high",
        "Brazilian Basketball Confederation Category A-1 adult athletes / national team — outside 5–22."),
    "29190193": ("screened_excluded", "E-offtop", "high",
        "Dogfighting injuries — animal subjects, off-topic (§3.1)."),
    "32134033": ("screened_excluded", "E-noprim", "high",
        "Awareness/knowledge survey of sports teachers; no athlete-level injury counts."),
    "33377302": ("screened_excluded", "E-age", "high",
        "Professional alpine ski racers worldwide; professional adults, outside 5–22."),
    "34257165": ("screened_excluded", "E-noprim", "high",
        "Editorial 'Revisiting Sports Dentistry' — no primary epidemiology data; review-type content."),
    "35802850": ("screened_excluded", "E-noprim", "high",
        "Knowledge survey of field hockey coaches — coaches, not athletes; no athlete-level injury counts."),
    "36479391": ("screened_excluded", "E-noprim", "high",
        "Awareness study of Libyan contact-sport coaches; no athlete-level injury counts."),
    "38729211": ("screened_excluded", "E-offtop", "high",
        "US Army Special Operations military working DOGS — animal subjects, off-topic."),
    "40267058": ("screened_excluded", "E-age", "high",
        "Adult Gaelic football athletes mouthguard compliance; population explicitly adult."),
    "40919643": ("screened_excluded", "E-noprim", "high",
        "Survey of German elite team SUPERVISORS — preventive knowledge of medical teams, not athlete-level injury counts."),
    "26545276": ("screened_excluded", "E-noprim", "high",
        "Clinical review article on splinting rationale for luxated/avulsed teeth — review content, no primary epidemiology."),
    "27875057": ("screened_excluded", "E-noprim", "high",
        "NATA Position Statement — clinical recommendations / consensus document, not primary epidemiologic data."),
    "23998194": ("screened_excluded", "E-offtop", "high",
        "Birth order as risk factor for dental trauma in 1282 Swiss children; non-sport-specific risk factor study, sport-related subset not the focus."),

    # --------------------- NEEDS HUMAN REVIEW ---------------------

    "11678537": ("needs_human_review", "R-data", "medium",
        "n=150 Ankara children TDI study; abstract does not isolate sport-related subset — confirm in full text whether sport-related counts are extractable."),
    "11766091": ("needs_human_review", "R-mixed", "medium",
        "n=250 patients ages 1–59 Brazil; sport = 3.6% of causes — full text needed to extract youth (5–22) subset."),
    "11880801": ("needs_human_review", "R-age", "medium",
        "Finland ice hockey 1991–1992 insurance dataset (n=479 injured); abstract does not state age distribution — likely includes youth + adult, full text needed."),
    "12017183": ("needs_human_review", "R-data", "medium",
        "Dicle University 1995–98 pediatric dental fractures; ages 9–11 peak. Sport-related subset not isolated in abstract — confirm in full text."),
    "12139268": ("needs_human_review", "R-mixed", "medium",
        "SE Queensland 1998 dental trauma survey, ages 1–64; 16–20 group reported as sport-related — youth subset extractable but needs full text."),
    "12154770": ("needs_human_review", "R-age", "medium",
        "Professional and semi-professional contact-sport athletes — age range not stated; full text needed to confirm any youth (5–22) data."),
    "12656848": ("needs_human_review", "R-data", "medium",
        "University of Jordan pediatric dentistry 1997–2000, ages 10–12 peak; sport-related etiology not isolated in abstract."),
    "15362317": ("needs_human_review", "R-data", "medium",
        "Australian Football Injury Prevention Project RCT; abstract reports MG compliance, not injury counts — full text may contain dental injury outcome data."),
    "15643760": ("needs_human_review", "R-data", "medium",
        "11–13 yr Brazilian schoolchildren; 'physical leisure activities' 28.9% but specific sport-related counts not isolated."),
    "15853840": ("needs_human_review", "R-data", "medium",
        "5th–6th grade Jerusalem schoolchildren n=1195; sport mentioned among reasons but not isolated as primary data."),
    "16711635": ("screened_excluded", "E-age", "high",
        "Ontario adults aged 18–50; majority outside 5–22 range; sport-related subset for 18–22 may be too small/unclear from abstract."),
    "16872385": ("needs_human_review", "R-data", "medium",
        "12-yr Brazilian schoolchildren TDI; abstract focuses on overjet risk factor — full text needed for sport-related subset counts."),
    "17194069": ("needs_human_review", "R-data", "medium",
        "n=2725 Thai children 11–13; sport-related subset not isolated in abstract."),
    "17227375": ("needs_human_review", "R-data", "medium",
        "Mouthguard effect on neurocognitive deficits after concussion; primary outcome is concussion neurocog, dental injury data may be secondary in full text."),
    "17511835": ("needs_human_review", "R-age", "medium",
        "Inline skating Switzerland + Germany; age range not in abstract — could be predominantly adult."),
    "17846669": ("needs_human_review", "R-age", "medium",
        "n=370 male enrollees National Cadet Corps India; age range not stated — NCC enrollees often 13–22, but needs verification."),
    "18173668": ("needs_human_review", "R-data", "medium",
        "Children's Hospital Buffalo pediatric dental trauma requiring fixation; sport-related subset not isolated in abstract."),
    "18352919": ("needs_human_review", "R-mixed", "medium",
        "Otago NZ 2000–2004 dental school, ages 2–86 peak 16–25; youth (5–22) subset overlaps but full text needed to extract."),
    "18721342": ("needs_human_review", "R-age", "medium",
        "China basketball players n=236, 77 professional; age range not stated."),
    "18821955": ("needs_human_review", "R-age", "medium",
        "Mountain biking Switzerland/Austria/Germany/Italy n=423 males; age range not in abstract."),
    "19021650": ("needs_human_review", "R-data", "medium",
        "Czech 90 avulsed permanent teeth in 58 children — youth fits, but sport-related subset not isolated in abstract."),
    "19021660": ("needs_human_review", "R-age", "medium",
        "Australian rural dental trauma — age range not stated in abstract excerpt."),
    "19615582": ("needs_human_review", "R-mixed", "medium",
        "n=273 facial fracture patients Switzerland — age range not stated, could include adults."),
    "20089070": ("needs_human_review", "R-data", "medium",
        "Yazd Iran 9–14 yr schoolchildren TDI; sport-related subset not isolated in abstract."),
    "20572841": ("needs_human_review", "R-age", "medium",
        "Pan American Games athletes 2007 — adult/elite athletes, likely mostly outside 5–22."),
    "20666978": ("needs_human_review", "R-data", "medium",
        "n=1612 11–14 yr Brazilian schoolchildren TDI; sport-related subset not isolated."),
    "20669600": ("needs_human_review", "R-age", "medium",
        "Hurling injuries Mid-Western Regional Hospital Limerick n=70; age range not stated."),
    "20946344": ("needs_human_review", "R-mixed", "medium",
        "n=384 patients ages 7–65, 66% children — youth subset extractable but full text needed."),
    "21063551": ("needs_human_review", "R-age", "medium",
        "n=120 male combat sport athletes (boxing/taekwondo/kickboxing/Muay Thai) — age range not stated."),
    "21199336": ("needs_human_review", "R-age", "medium",
        "Floorball Switzerland + Sweden n=608 (565 athletes + 43 coaches); age range not stated."),
    "21382033": ("needs_human_review", "R-age", "medium",
        "Basketball players Benin City Nigeria — age range not stated in abstract."),
    "21755701": ("needs_human_review", "R-data", "medium",
        "Junior AND senior basketball players orofacial injuries; junior subset likely extractable but abstract does not give counts by group."),
    "21790975": ("needs_human_review", "R-data", "medium",
        "n=387 Brazilian adolescents 12–15; focus on 'non-accidental collision' — sport-related subset unclear."),
    "21880516": ("needs_human_review", "R-data", "medium",
        "n=502 schoolchildren 11–14 orthodontic risk factor study; sport involvement not in abstract."),
    "22107072": ("needs_human_review", "R-age", "medium",
        "Water polo Switzerland n=415 players from 6 divisions — likely mostly adult but youth subset may exist."),
    "22882839": ("needs_human_review", "R-age", "medium",
        "Para-Pan American Games athletes Rio — adults likely dominate; youth (16–22) subset may be present."),
    "23534038": ("needs_human_review", "R-data", "medium",
        "n=2560 12-yr Jordanian schoolchildren TDI; sport-related subset not isolated in abstract."),
    "24198704": ("needs_human_review", "R-age", "medium",
        "Iranian women Shotokan karate national championships 'in all age groups'; youth subset may be extractable from full text."),
    "24505897": ("needs_human_review", "R-data", "medium",
        "n=372 Romanian 8–20 yr; sport-related subset not isolated."),
    "25244279": ("needs_human_review", "R-data", "medium",
        "Samsun Turkey 2007–11 emergency dental trauma in children n=320; sport-related subset not isolated."),
    "25536987": ("needs_human_review", "R-age", "medium",
        "Zagreb amateur (n=60) + professional (n=135) basketball — adult-dominant likely; youth subset extractable only if amateurs include U18."),
    "25600092": ("needs_human_review", "R-mixed", "medium",
        "n=15941 Special Olympics athletes Europe/Eurasia — mixed ages (Special Olympics allows adults too); youth subset extractable."),
    "25721283": ("needs_human_review", "R-age", "medium",
        "Royal Dental Hospital Melbourne 2009–2012 emergency surveillance audit — age range not in abstract."),
    "26058666": ("needs_human_review", "R-age", "medium",
        "Rugby players Malaysia, aged 16+ — most likely adult, but 16–22 subset extractable."),
    "26542314": ("needs_human_review", "R-age", "medium",
        "Showjumping Switzerland/France/Germany n=608 — age range not in abstract."),
    "26545273": ("needs_human_review", "R-data", "medium",
        "HS athletes US mouthguard mandate review — may be policy overview without primary injury data; full text needed."),
    "26678302": ("needs_human_review", "R-age", "medium",
        "Swiss boxing clubs n=217 boxers; age range not in abstract."),
    "26939219": ("needs_human_review", "R-data", "medium",
        "Cameroon 12–13 schoolchildren incisor trauma n=2287; sport-related subset not isolated."),
    "27622524": ("needs_human_review", "R-age", "medium",
        "Team handball 'top athletes' n=542; age range not in abstract — likely senior."),
    "28160512": ("needs_human_review", "R-age", "medium",
        "Professional handball n=100; professional = adult likely."),
    "28969286": ("needs_human_review", "R-data", "medium",
        "Indian adolescents TDI vs self-esteem; sport-related subset not isolated."),
    "30156365": ("needs_human_review", "R-age", "medium",
        "Water polo n=347 players 2015–16 season; age range not in abstract."),
    "30431180": ("needs_human_review", "R-mixed", "medium",
        "Israeli Special Olympics 2016 — Special Olympics athletes mixed ages (8+ allowed); youth subset extractable."),
    "31994310": ("needs_human_review", "R-age", "medium",
        "Bern Switzerland judo n=382; age range not in abstract."),
    "33188561": ("needs_human_review", "R-age", "medium",
        "CrossFit practitioners online survey; population likely adult (self-selected practitioners)."),
    "33220143": ("needs_human_review", "R-age", "medium",
        "Elite cross-country mountain biking + field hockey athletes pre-Olympic competitions Rio; elite likely adult, but some youth elite athletes may be present."),
    "34047017": ("needs_human_review", "R-age", "medium",
        "Lorraine France handball n=>15 yr — primarily adult; 15–22 subset extractable."),
    "34343071": ("needs_human_review", "R-age", "medium",
        "Ice hockey n=169 online survey — age range not in abstract."),
    "36327493": ("needs_human_review", "R-age", "medium",
        "Australian sub-elite football (soccer) injury insurance 2018–2020 — age group breakdown reported but exact ranges not in abstract."),
    "36394781": ("needs_human_review", "R-data", "medium",
        "Irish children contact sport (Gaelic football) MG assessment — primary outcome is MG design adequacy, not injury counts."),
    "36538371": ("needs_human_review", "R-age", "medium",
        "Finnish trauma centre 2013–2020 ice hockey facial fractures; professional + recreational — youth subset extractable."),
    "36922269": ("needs_human_review", "R-age", "medium",
        "Kabaddi players Delhi-NCR — age range not in abstract; likely mixed youth/adult."),
    "37055924": ("needs_human_review", "R-age", "medium",
        "Malaysian para-athletes n=61 — age range not in abstract."),
    "37341423": ("needs_human_review", "R-age", "medium",
        "Croatian soccer all leagues n=393 — age range not in abstract."),
    "37431232": ("needs_human_review", "R-age", "medium",
        "Australian non-professional football insurance 2018–2020; age categories reported but ranges unclear."),
    "37791703": ("needs_human_review", "R-age", "medium",
        "Ladies Gaelic football MG cost reduction; abstract truncated in our dump — Ladies GAA is adult, but youth subset may exist."),
    "39452438": ("needs_human_review", "R-mixed", "medium",
        "Italian kickboxing athletes n=142 ages 5–65 — youth subset (5–22) extractable but needs full text."),
    "39630092": ("needs_human_review", "R-age", "medium",
        "German elite athletes 18–35; 18–22 subset within scope but mixed-ages population."),
    "40662680": ("needs_human_review", "R-age", "medium",
        "Swiss Muay Thai/K-1/Kickboxing n=440 martial artists — age range not in abstract."),
}

# Remove the placeholder dummy entries so they don't accidentally make it into the run.
MANUAL_DECISIONS.pop("11499758a_dup_check", None)
MANUAL_DECISIONS.pop("16809595_v2", None)
